// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_matmul_dataflow_in_loop_CallBlockMatmul_1 (
        ap_clk,
        ap_rst,
        m_axi_MatA_AWVALID,
        m_axi_MatA_AWREADY,
        m_axi_MatA_AWADDR,
        m_axi_MatA_AWID,
        m_axi_MatA_AWLEN,
        m_axi_MatA_AWSIZE,
        m_axi_MatA_AWBURST,
        m_axi_MatA_AWLOCK,
        m_axi_MatA_AWCACHE,
        m_axi_MatA_AWPROT,
        m_axi_MatA_AWQOS,
        m_axi_MatA_AWREGION,
        m_axi_MatA_AWUSER,
        m_axi_MatA_WVALID,
        m_axi_MatA_WREADY,
        m_axi_MatA_WDATA,
        m_axi_MatA_WSTRB,
        m_axi_MatA_WLAST,
        m_axi_MatA_WID,
        m_axi_MatA_WUSER,
        m_axi_MatA_ARVALID,
        m_axi_MatA_ARREADY,
        m_axi_MatA_ARADDR,
        m_axi_MatA_ARID,
        m_axi_MatA_ARLEN,
        m_axi_MatA_ARSIZE,
        m_axi_MatA_ARBURST,
        m_axi_MatA_ARLOCK,
        m_axi_MatA_ARCACHE,
        m_axi_MatA_ARPROT,
        m_axi_MatA_ARQOS,
        m_axi_MatA_ARREGION,
        m_axi_MatA_ARUSER,
        m_axi_MatA_RVALID,
        m_axi_MatA_RREADY,
        m_axi_MatA_RDATA,
        m_axi_MatA_RLAST,
        m_axi_MatA_RID,
        m_axi_MatA_RFIFONUM,
        m_axi_MatA_RUSER,
        m_axi_MatA_RRESP,
        m_axi_MatA_BVALID,
        m_axi_MatA_BREADY,
        m_axi_MatA_BRESP,
        m_axi_MatA_BID,
        m_axi_MatA_BUSER,
        MatA_DRAM,
        m_axi_MatB_AWVALID,
        m_axi_MatB_AWREADY,
        m_axi_MatB_AWADDR,
        m_axi_MatB_AWID,
        m_axi_MatB_AWLEN,
        m_axi_MatB_AWSIZE,
        m_axi_MatB_AWBURST,
        m_axi_MatB_AWLOCK,
        m_axi_MatB_AWCACHE,
        m_axi_MatB_AWPROT,
        m_axi_MatB_AWQOS,
        m_axi_MatB_AWREGION,
        m_axi_MatB_AWUSER,
        m_axi_MatB_WVALID,
        m_axi_MatB_WREADY,
        m_axi_MatB_WDATA,
        m_axi_MatB_WSTRB,
        m_axi_MatB_WLAST,
        m_axi_MatB_WID,
        m_axi_MatB_WUSER,
        m_axi_MatB_ARVALID,
        m_axi_MatB_ARREADY,
        m_axi_MatB_ARADDR,
        m_axi_MatB_ARID,
        m_axi_MatB_ARLEN,
        m_axi_MatB_ARSIZE,
        m_axi_MatB_ARBURST,
        m_axi_MatB_ARLOCK,
        m_axi_MatB_ARCACHE,
        m_axi_MatB_ARPROT,
        m_axi_MatB_ARQOS,
        m_axi_MatB_ARREGION,
        m_axi_MatB_ARUSER,
        m_axi_MatB_RVALID,
        m_axi_MatB_RREADY,
        m_axi_MatB_RDATA,
        m_axi_MatB_RLAST,
        m_axi_MatB_RID,
        m_axi_MatB_RFIFONUM,
        m_axi_MatB_RUSER,
        m_axi_MatB_RRESP,
        m_axi_MatB_BVALID,
        m_axi_MatB_BREADY,
        m_axi_MatB_BRESP,
        m_axi_MatB_BID,
        m_axi_MatB_BUSER,
        MatB_DRAM,
        counter_0,
        m_axi_MatC_AWVALID,
        m_axi_MatC_AWREADY,
        m_axi_MatC_AWADDR,
        m_axi_MatC_AWID,
        m_axi_MatC_AWLEN,
        m_axi_MatC_AWSIZE,
        m_axi_MatC_AWBURST,
        m_axi_MatC_AWLOCK,
        m_axi_MatC_AWCACHE,
        m_axi_MatC_AWPROT,
        m_axi_MatC_AWQOS,
        m_axi_MatC_AWREGION,
        m_axi_MatC_AWUSER,
        m_axi_MatC_WVALID,
        m_axi_MatC_WREADY,
        m_axi_MatC_WDATA,
        m_axi_MatC_WSTRB,
        m_axi_MatC_WLAST,
        m_axi_MatC_WID,
        m_axi_MatC_WUSER,
        m_axi_MatC_ARVALID,
        m_axi_MatC_ARREADY,
        m_axi_MatC_ARADDR,
        m_axi_MatC_ARID,
        m_axi_MatC_ARLEN,
        m_axi_MatC_ARSIZE,
        m_axi_MatC_ARBURST,
        m_axi_MatC_ARLOCK,
        m_axi_MatC_ARCACHE,
        m_axi_MatC_ARPROT,
        m_axi_MatC_ARQOS,
        m_axi_MatC_ARREGION,
        m_axi_MatC_ARUSER,
        m_axi_MatC_RVALID,
        m_axi_MatC_RREADY,
        m_axi_MatC_RDATA,
        m_axi_MatC_RLAST,
        m_axi_MatC_RID,
        m_axi_MatC_RFIFONUM,
        m_axi_MatC_RUSER,
        m_axi_MatC_RRESP,
        m_axi_MatC_BVALID,
        m_axi_MatC_BREADY,
        m_axi_MatC_BRESP,
        m_axi_MatC_BID,
        m_axi_MatC_BUSER,
        MatC_DRAM,
        MatC_DRAM_ap_vld,
        ap_start,
        MatA_DRAM_ap_vld,
        MatB_DRAM_ap_vld,
        counter_0_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_clk;
input   ap_rst;
output   m_axi_MatA_AWVALID;
input   m_axi_MatA_AWREADY;
output  [63:0] m_axi_MatA_AWADDR;
output  [0:0] m_axi_MatA_AWID;
output  [31:0] m_axi_MatA_AWLEN;
output  [2:0] m_axi_MatA_AWSIZE;
output  [1:0] m_axi_MatA_AWBURST;
output  [1:0] m_axi_MatA_AWLOCK;
output  [3:0] m_axi_MatA_AWCACHE;
output  [2:0] m_axi_MatA_AWPROT;
output  [3:0] m_axi_MatA_AWQOS;
output  [3:0] m_axi_MatA_AWREGION;
output  [0:0] m_axi_MatA_AWUSER;
output   m_axi_MatA_WVALID;
input   m_axi_MatA_WREADY;
output  [15:0] m_axi_MatA_WDATA;
output  [1:0] m_axi_MatA_WSTRB;
output   m_axi_MatA_WLAST;
output  [0:0] m_axi_MatA_WID;
output  [0:0] m_axi_MatA_WUSER;
output   m_axi_MatA_ARVALID;
input   m_axi_MatA_ARREADY;
output  [63:0] m_axi_MatA_ARADDR;
output  [0:0] m_axi_MatA_ARID;
output  [31:0] m_axi_MatA_ARLEN;
output  [2:0] m_axi_MatA_ARSIZE;
output  [1:0] m_axi_MatA_ARBURST;
output  [1:0] m_axi_MatA_ARLOCK;
output  [3:0] m_axi_MatA_ARCACHE;
output  [2:0] m_axi_MatA_ARPROT;
output  [3:0] m_axi_MatA_ARQOS;
output  [3:0] m_axi_MatA_ARREGION;
output  [0:0] m_axi_MatA_ARUSER;
input   m_axi_MatA_RVALID;
output   m_axi_MatA_RREADY;
input  [15:0] m_axi_MatA_RDATA;
input   m_axi_MatA_RLAST;
input  [0:0] m_axi_MatA_RID;
input  [9:0] m_axi_MatA_RFIFONUM;
input  [0:0] m_axi_MatA_RUSER;
input  [1:0] m_axi_MatA_RRESP;
input   m_axi_MatA_BVALID;
output   m_axi_MatA_BREADY;
input  [1:0] m_axi_MatA_BRESP;
input  [0:0] m_axi_MatA_BID;
input  [0:0] m_axi_MatA_BUSER;
input  [63:0] MatA_DRAM;
output   m_axi_MatB_AWVALID;
input   m_axi_MatB_AWREADY;
output  [63:0] m_axi_MatB_AWADDR;
output  [0:0] m_axi_MatB_AWID;
output  [31:0] m_axi_MatB_AWLEN;
output  [2:0] m_axi_MatB_AWSIZE;
output  [1:0] m_axi_MatB_AWBURST;
output  [1:0] m_axi_MatB_AWLOCK;
output  [3:0] m_axi_MatB_AWCACHE;
output  [2:0] m_axi_MatB_AWPROT;
output  [3:0] m_axi_MatB_AWQOS;
output  [3:0] m_axi_MatB_AWREGION;
output  [0:0] m_axi_MatB_AWUSER;
output   m_axi_MatB_WVALID;
input   m_axi_MatB_WREADY;
output  [15:0] m_axi_MatB_WDATA;
output  [1:0] m_axi_MatB_WSTRB;
output   m_axi_MatB_WLAST;
output  [0:0] m_axi_MatB_WID;
output  [0:0] m_axi_MatB_WUSER;
output   m_axi_MatB_ARVALID;
input   m_axi_MatB_ARREADY;
output  [63:0] m_axi_MatB_ARADDR;
output  [0:0] m_axi_MatB_ARID;
output  [31:0] m_axi_MatB_ARLEN;
output  [2:0] m_axi_MatB_ARSIZE;
output  [1:0] m_axi_MatB_ARBURST;
output  [1:0] m_axi_MatB_ARLOCK;
output  [3:0] m_axi_MatB_ARCACHE;
output  [2:0] m_axi_MatB_ARPROT;
output  [3:0] m_axi_MatB_ARQOS;
output  [3:0] m_axi_MatB_ARREGION;
output  [0:0] m_axi_MatB_ARUSER;
input   m_axi_MatB_RVALID;
output   m_axi_MatB_RREADY;
input  [15:0] m_axi_MatB_RDATA;
input   m_axi_MatB_RLAST;
input  [0:0] m_axi_MatB_RID;
input  [9:0] m_axi_MatB_RFIFONUM;
input  [0:0] m_axi_MatB_RUSER;
input  [1:0] m_axi_MatB_RRESP;
input   m_axi_MatB_BVALID;
output   m_axi_MatB_BREADY;
input  [1:0] m_axi_MatB_BRESP;
input  [0:0] m_axi_MatB_BID;
input  [0:0] m_axi_MatB_BUSER;
input  [63:0] MatB_DRAM;
input  [10:0] counter_0;
output   m_axi_MatC_AWVALID;
input   m_axi_MatC_AWREADY;
output  [63:0] m_axi_MatC_AWADDR;
output  [0:0] m_axi_MatC_AWID;
output  [31:0] m_axi_MatC_AWLEN;
output  [2:0] m_axi_MatC_AWSIZE;
output  [1:0] m_axi_MatC_AWBURST;
output  [1:0] m_axi_MatC_AWLOCK;
output  [3:0] m_axi_MatC_AWCACHE;
output  [2:0] m_axi_MatC_AWPROT;
output  [3:0] m_axi_MatC_AWQOS;
output  [3:0] m_axi_MatC_AWREGION;
output  [0:0] m_axi_MatC_AWUSER;
output   m_axi_MatC_WVALID;
input   m_axi_MatC_WREADY;
output  [15:0] m_axi_MatC_WDATA;
output  [1:0] m_axi_MatC_WSTRB;
output   m_axi_MatC_WLAST;
output  [0:0] m_axi_MatC_WID;
output  [0:0] m_axi_MatC_WUSER;
output   m_axi_MatC_ARVALID;
input   m_axi_MatC_ARREADY;
output  [63:0] m_axi_MatC_ARADDR;
output  [0:0] m_axi_MatC_ARID;
output  [31:0] m_axi_MatC_ARLEN;
output  [2:0] m_axi_MatC_ARSIZE;
output  [1:0] m_axi_MatC_ARBURST;
output  [1:0] m_axi_MatC_ARLOCK;
output  [3:0] m_axi_MatC_ARCACHE;
output  [2:0] m_axi_MatC_ARPROT;
output  [3:0] m_axi_MatC_ARQOS;
output  [3:0] m_axi_MatC_ARREGION;
output  [0:0] m_axi_MatC_ARUSER;
input   m_axi_MatC_RVALID;
output   m_axi_MatC_RREADY;
input  [15:0] m_axi_MatC_RDATA;
input   m_axi_MatC_RLAST;
input  [0:0] m_axi_MatC_RID;
input  [9:0] m_axi_MatC_RFIFONUM;
input  [0:0] m_axi_MatC_RUSER;
input  [1:0] m_axi_MatC_RRESP;
input   m_axi_MatC_BVALID;
output   m_axi_MatC_BREADY;
input  [1:0] m_axi_MatC_BRESP;
input  [0:0] m_axi_MatC_BID;
input  [0:0] m_axi_MatC_BUSER;
input  [63:0] MatC_DRAM;
input   MatC_DRAM_ap_vld;
input   ap_start;
input   MatA_DRAM_ap_vld;
input   MatB_DRAM_ap_vld;
input   counter_0_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [15:0] MatC_BRAM_i_q0;
wire   [15:0] MatC_BRAM_t_q0;
wire   [15:0] MatB_BRAM_i_q0;
wire   [15:0] MatB_BRAM_i_q1;
wire   [15:0] MatB_BRAM_t_q0;
wire   [15:0] MatB_BRAM_t_q1;
wire   [15:0] MatB_BRAM_1_26_i_q0;
wire   [15:0] MatB_BRAM_1_26_i_q1;
wire   [15:0] MatB_BRAM_1_26_t_q0;
wire   [15:0] MatB_BRAM_1_26_t_q1;
wire   [15:0] MatB_BRAM_1_i_q0;
wire   [15:0] MatB_BRAM_1_i_q1;
wire   [15:0] MatB_BRAM_1_t_q0;
wire   [15:0] MatB_BRAM_1_t_q1;
wire   [15:0] MatB_BRAM_2_i_q0;
wire   [15:0] MatB_BRAM_2_i_q1;
wire   [15:0] MatB_BRAM_2_t_q0;
wire   [15:0] MatB_BRAM_2_t_q1;
wire   [15:0] MatA_BRAM_i_q0;
wire   [15:0] MatA_BRAM_i_q1;
wire   [15:0] MatA_BRAM_t_q0;
wire   [15:0] MatA_BRAM_t_q1;
wire   [15:0] MatA_BRAM_1_27_i_q0;
wire   [15:0] MatA_BRAM_1_27_i_q1;
wire   [15:0] MatA_BRAM_1_27_t_q0;
wire   [15:0] MatA_BRAM_1_27_t_q1;
wire   [15:0] MatA_BRAM_1_i_q0;
wire   [15:0] MatA_BRAM_1_i_q1;
wire   [15:0] MatA_BRAM_1_t_q0;
wire   [15:0] MatA_BRAM_1_t_q1;
wire   [15:0] MatA_BRAM_2_i_q0;
wire   [15:0] MatA_BRAM_2_i_q1;
wire   [15:0] MatA_BRAM_2_t_q0;
wire   [15:0] MatA_BRAM_2_t_q1;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire   [63:0] entry_proc_U0_MatC_DRAM_c_din;
wire    entry_proc_U0_MatC_DRAM_c_write;
wire    LoadMatricesFromDRAMToBRAM_U0_ap_start;
wire    LoadMatricesFromDRAMToBRAM_U0_ap_done;
wire    LoadMatricesFromDRAMToBRAM_U0_ap_continue;
wire    LoadMatricesFromDRAMToBRAM_U0_ap_idle;
wire    LoadMatricesFromDRAMToBRAM_U0_ap_ready;
wire   [7:0] LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_address0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_ce0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_we0;
wire   [15:0] LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_d0;
wire   [7:0] LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_address0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_ce0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_we0;
wire   [15:0] LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_d0;
wire   [7:0] LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_address0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_ce0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_we0;
wire   [15:0] LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_d0;
wire   [7:0] LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_address0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_ce0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_we0;
wire   [15:0] LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_d0;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWVALID;
wire   [63:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWADDR;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWID;
wire   [31:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWLEN;
wire   [2:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWSIZE;
wire   [1:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWBURST;
wire   [1:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWLOCK;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWCACHE;
wire   [2:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWPROT;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWQOS;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWREGION;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWUSER;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WVALID;
wire   [15:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WDATA;
wire   [1:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WSTRB;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WLAST;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WID;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WUSER;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARVALID;
wire   [63:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARADDR;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARID;
wire   [31:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARLEN;
wire   [2:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARSIZE;
wire   [1:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARBURST;
wire   [1:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARLOCK;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARCACHE;
wire   [2:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARPROT;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARQOS;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARREGION;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARUSER;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_RREADY;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_BREADY;
wire   [7:0] LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_address0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_ce0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_we0;
wire   [15:0] LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_d0;
wire   [7:0] LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_address0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_ce0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_we0;
wire   [15:0] LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_d0;
wire   [7:0] LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_address0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_ce0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_we0;
wire   [15:0] LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_d0;
wire   [7:0] LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_address0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_ce0;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_we0;
wire   [15:0] LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_d0;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWVALID;
wire   [63:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWADDR;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWID;
wire   [31:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWLEN;
wire   [2:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWSIZE;
wire   [1:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWBURST;
wire   [1:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWLOCK;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWCACHE;
wire   [2:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWPROT;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWQOS;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWREGION;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWUSER;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WVALID;
wire   [15:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WDATA;
wire   [1:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WSTRB;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WLAST;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WID;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WUSER;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARVALID;
wire   [63:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARADDR;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARID;
wire   [31:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARLEN;
wire   [2:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARSIZE;
wire   [1:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARBURST;
wire   [1:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARLOCK;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARCACHE;
wire   [2:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARPROT;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARQOS;
wire   [3:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARREGION;
wire   [0:0] LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARUSER;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_RREADY;
wire    LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_BREADY;
wire   [10:0] LoadMatricesFromDRAMToBRAM_U0_ap_return;
wire    ap_channel_done_counter_0_c_channel;
wire    counter_0_c_channel_full_n;
reg    ap_sync_reg_channel_write_counter_0_c_channel;
wire    ap_sync_channel_write_counter_0_c_channel;
wire    ap_channel_done_MatB_BRAM;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_full_n;
reg    ap_sync_reg_channel_write_MatB_BRAM;
wire    ap_sync_channel_write_MatB_BRAM;
wire    ap_channel_done_MatB_BRAM_1_26;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_full_n;
reg    ap_sync_reg_channel_write_MatB_BRAM_1_26;
wire    ap_sync_channel_write_MatB_BRAM_1_26;
wire    ap_channel_done_MatB_BRAM_1;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_full_n;
reg    ap_sync_reg_channel_write_MatB_BRAM_1;
wire    ap_sync_channel_write_MatB_BRAM_1;
wire    ap_channel_done_MatB_BRAM_2;
wire    LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_full_n;
reg    ap_sync_reg_channel_write_MatB_BRAM_2;
wire    ap_sync_channel_write_MatB_BRAM_2;
wire    ap_channel_done_MatA_BRAM;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_full_n;
reg    ap_sync_reg_channel_write_MatA_BRAM;
wire    ap_sync_channel_write_MatA_BRAM;
wire    ap_channel_done_MatA_BRAM_1_27;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_full_n;
reg    ap_sync_reg_channel_write_MatA_BRAM_1_27;
wire    ap_sync_channel_write_MatA_BRAM_1_27;
wire    ap_channel_done_MatA_BRAM_1;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_full_n;
reg    ap_sync_reg_channel_write_MatA_BRAM_1;
wire    ap_sync_channel_write_MatA_BRAM_1;
wire    ap_channel_done_MatA_BRAM_2;
wire    LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_full_n;
reg    ap_sync_reg_channel_write_MatA_BRAM_2;
wire    ap_sync_channel_write_MatA_BRAM_2;
wire    PerformMatrixCalculation_U0_ap_start;
wire    PerformMatrixCalculation_U0_ap_done;
wire    PerformMatrixCalculation_U0_ap_continue;
wire    PerformMatrixCalculation_U0_ap_idle;
wire    PerformMatrixCalculation_U0_ap_ready;
wire   [7:0] PerformMatrixCalculation_U0_MatA_BRAM_0_address0;
wire    PerformMatrixCalculation_U0_MatA_BRAM_0_ce0;
wire   [7:0] PerformMatrixCalculation_U0_MatA_BRAM_0_address1;
wire    PerformMatrixCalculation_U0_MatA_BRAM_0_ce1;
wire   [7:0] PerformMatrixCalculation_U0_MatA_BRAM_1_address0;
wire    PerformMatrixCalculation_U0_MatA_BRAM_1_ce0;
wire   [7:0] PerformMatrixCalculation_U0_MatA_BRAM_1_address1;
wire    PerformMatrixCalculation_U0_MatA_BRAM_1_ce1;
wire   [7:0] PerformMatrixCalculation_U0_MatA_BRAM_2_address0;
wire    PerformMatrixCalculation_U0_MatA_BRAM_2_ce0;
wire   [7:0] PerformMatrixCalculation_U0_MatA_BRAM_2_address1;
wire    PerformMatrixCalculation_U0_MatA_BRAM_2_ce1;
wire   [7:0] PerformMatrixCalculation_U0_MatA_BRAM_3_address0;
wire    PerformMatrixCalculation_U0_MatA_BRAM_3_ce0;
wire   [7:0] PerformMatrixCalculation_U0_MatA_BRAM_3_address1;
wire    PerformMatrixCalculation_U0_MatA_BRAM_3_ce1;
wire   [7:0] PerformMatrixCalculation_U0_MatB_BRAM_0_address0;
wire    PerformMatrixCalculation_U0_MatB_BRAM_0_ce0;
wire   [7:0] PerformMatrixCalculation_U0_MatB_BRAM_0_address1;
wire    PerformMatrixCalculation_U0_MatB_BRAM_0_ce1;
wire   [7:0] PerformMatrixCalculation_U0_MatB_BRAM_1_address0;
wire    PerformMatrixCalculation_U0_MatB_BRAM_1_ce0;
wire   [7:0] PerformMatrixCalculation_U0_MatB_BRAM_1_address1;
wire    PerformMatrixCalculation_U0_MatB_BRAM_1_ce1;
wire   [7:0] PerformMatrixCalculation_U0_MatB_BRAM_2_address0;
wire    PerformMatrixCalculation_U0_MatB_BRAM_2_ce0;
wire   [7:0] PerformMatrixCalculation_U0_MatB_BRAM_2_address1;
wire    PerformMatrixCalculation_U0_MatB_BRAM_2_ce1;
wire   [7:0] PerformMatrixCalculation_U0_MatB_BRAM_3_address0;
wire    PerformMatrixCalculation_U0_MatB_BRAM_3_ce0;
wire   [7:0] PerformMatrixCalculation_U0_MatB_BRAM_3_address1;
wire    PerformMatrixCalculation_U0_MatB_BRAM_3_ce1;
wire   [3:0] PerformMatrixCalculation_U0_MatC_BRAM_address0;
wire    PerformMatrixCalculation_U0_MatC_BRAM_ce0;
wire    PerformMatrixCalculation_U0_MatC_BRAM_we0;
wire   [15:0] PerformMatrixCalculation_U0_MatC_BRAM_d0;
wire    LoadMatricesFromBRAMToDRAM_U0_ap_start;
wire    LoadMatricesFromBRAMToDRAM_U0_ap_done;
wire    LoadMatricesFromBRAMToDRAM_U0_ap_continue;
wire    LoadMatricesFromBRAMToDRAM_U0_ap_idle;
wire    LoadMatricesFromBRAMToDRAM_U0_ap_ready;
wire   [3:0] LoadMatricesFromBRAMToDRAM_U0_MatC_BRAM_address0;
wire    LoadMatricesFromBRAMToDRAM_U0_MatC_BRAM_ce0;
wire    LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWVALID;
wire   [63:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWADDR;
wire   [0:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWID;
wire   [31:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWLEN;
wire   [2:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWSIZE;
wire   [1:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWBURST;
wire   [1:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWLOCK;
wire   [3:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWCACHE;
wire   [2:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWPROT;
wire   [3:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWQOS;
wire   [3:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWREGION;
wire   [0:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWUSER;
wire    LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WVALID;
wire   [15:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WDATA;
wire   [1:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WSTRB;
wire    LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WLAST;
wire   [0:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WID;
wire   [0:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WUSER;
wire    LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARVALID;
wire   [63:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARADDR;
wire   [0:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARID;
wire   [31:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARLEN;
wire   [2:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARSIZE;
wire   [1:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARBURST;
wire   [1:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARLOCK;
wire   [3:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARCACHE;
wire   [2:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARPROT;
wire   [3:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARQOS;
wire   [3:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARREGION;
wire   [0:0] LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARUSER;
wire    LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_RREADY;
wire    LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_BREADY;
wire    LoadMatricesFromBRAMToDRAM_U0_MatC_DRAM_read;
wire    MatA_BRAM_2_i_full_n;
wire    MatA_BRAM_2_t_empty_n;
wire    MatA_BRAM_1_i_full_n;
wire    MatA_BRAM_1_t_empty_n;
wire    MatA_BRAM_1_27_i_full_n;
wire    MatA_BRAM_1_27_t_empty_n;
wire    MatA_BRAM_i_full_n;
wire    MatA_BRAM_t_empty_n;
wire    MatB_BRAM_2_i_full_n;
wire    MatB_BRAM_2_t_empty_n;
wire    MatB_BRAM_1_i_full_n;
wire    MatB_BRAM_1_t_empty_n;
wire    MatB_BRAM_1_26_i_full_n;
wire    MatB_BRAM_1_26_t_empty_n;
wire    MatB_BRAM_i_full_n;
wire    MatB_BRAM_t_empty_n;
wire    MatC_BRAM_i_full_n;
wire    MatC_BRAM_t_empty_n;
wire    MatC_DRAM_c_full_n;
wire   [63:0] MatC_DRAM_c_dout;
wire   [2:0] MatC_DRAM_c_num_data_valid;
wire   [2:0] MatC_DRAM_c_fifo_cap;
wire    MatC_DRAM_c_empty_n;
wire   [10:0] counter_0_c_channel_dout;
wire   [2:0] counter_0_c_channel_num_data_valid;
wire   [2:0] counter_0_c_channel_fifo_cap;
wire    counter_0_c_channel_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_LoadMatricesFromDRAMToBRAM_U0_ap_ready;
wire    ap_sync_LoadMatricesFromDRAMToBRAM_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_counter_0_c_channel = 1'b0;
#0 ap_sync_reg_channel_write_MatB_BRAM = 1'b0;
#0 ap_sync_reg_channel_write_MatB_BRAM_1_26 = 1'b0;
#0 ap_sync_reg_channel_write_MatB_BRAM_1 = 1'b0;
#0 ap_sync_reg_channel_write_MatB_BRAM_2 = 1'b0;
#0 ap_sync_reg_channel_write_MatA_BRAM = 1'b0;
#0 ap_sync_reg_channel_write_MatA_BRAM_1_27 = 1'b0;
#0 ap_sync_reg_channel_write_MatA_BRAM_1 = 1'b0;
#0 ap_sync_reg_channel_write_MatA_BRAM_2 = 1'b0;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_LoadMatricesFromDRAMToBRAM_U0_ap_ready = 1'b0;
end

real_matmul_dataflow_in_loop_CallBlockMatmul_1_MatC_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
MatC_BRAM_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(PerformMatrixCalculation_U0_MatC_BRAM_address0),
    .i_ce0(PerformMatrixCalculation_U0_MatC_BRAM_ce0),
    .i_we0(PerformMatrixCalculation_U0_MatC_BRAM_we0),
    .i_d0(PerformMatrixCalculation_U0_MatC_BRAM_d0),
    .i_q0(MatC_BRAM_i_q0),
    .t_address0(LoadMatricesFromBRAMToDRAM_U0_MatC_BRAM_address0),
    .t_ce0(LoadMatricesFromBRAMToDRAM_U0_MatC_BRAM_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(MatC_BRAM_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(MatC_BRAM_i_full_n),
    .i_write(PerformMatrixCalculation_U0_ap_done),
    .t_empty_n(MatC_BRAM_t_empty_n),
    .t_read(LoadMatricesFromBRAMToDRAM_U0_ap_ready)
);

real_matmul_dataflow_in_loop_CallBlockMatmul_1_MatB_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatB_BRAM_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_address0),
    .i_ce0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_ce0),
    .i_we0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_we0),
    .i_d0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_d0),
    .i_q0(MatB_BRAM_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(MatB_BRAM_i_q1),
    .t_address0(PerformMatrixCalculation_U0_MatB_BRAM_3_address0),
    .t_ce0(PerformMatrixCalculation_U0_MatB_BRAM_3_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(MatB_BRAM_t_q0),
    .t_address1(PerformMatrixCalculation_U0_MatB_BRAM_3_address1),
    .t_ce1(PerformMatrixCalculation_U0_MatB_BRAM_3_ce1),
    .t_q1(MatB_BRAM_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(MatB_BRAM_i_full_n),
    .i_write(ap_channel_done_MatB_BRAM),
    .t_empty_n(MatB_BRAM_t_empty_n),
    .t_read(PerformMatrixCalculation_U0_ap_ready)
);

real_matmul_dataflow_in_loop_CallBlockMatmul_1_MatB_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatB_BRAM_1_26_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_address0),
    .i_ce0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_ce0),
    .i_we0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_we0),
    .i_d0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_d0),
    .i_q0(MatB_BRAM_1_26_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(MatB_BRAM_1_26_i_q1),
    .t_address0(PerformMatrixCalculation_U0_MatB_BRAM_2_address0),
    .t_ce0(PerformMatrixCalculation_U0_MatB_BRAM_2_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(MatB_BRAM_1_26_t_q0),
    .t_address1(PerformMatrixCalculation_U0_MatB_BRAM_2_address1),
    .t_ce1(PerformMatrixCalculation_U0_MatB_BRAM_2_ce1),
    .t_q1(MatB_BRAM_1_26_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(MatB_BRAM_1_26_i_full_n),
    .i_write(ap_channel_done_MatB_BRAM_1_26),
    .t_empty_n(MatB_BRAM_1_26_t_empty_n),
    .t_read(PerformMatrixCalculation_U0_ap_ready)
);

real_matmul_dataflow_in_loop_CallBlockMatmul_1_MatB_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatB_BRAM_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_address0),
    .i_ce0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_ce0),
    .i_we0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_we0),
    .i_d0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_d0),
    .i_q0(MatB_BRAM_1_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(MatB_BRAM_1_i_q1),
    .t_address0(PerformMatrixCalculation_U0_MatB_BRAM_1_address0),
    .t_ce0(PerformMatrixCalculation_U0_MatB_BRAM_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(MatB_BRAM_1_t_q0),
    .t_address1(PerformMatrixCalculation_U0_MatB_BRAM_1_address1),
    .t_ce1(PerformMatrixCalculation_U0_MatB_BRAM_1_ce1),
    .t_q1(MatB_BRAM_1_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(MatB_BRAM_1_i_full_n),
    .i_write(ap_channel_done_MatB_BRAM_1),
    .t_empty_n(MatB_BRAM_1_t_empty_n),
    .t_read(PerformMatrixCalculation_U0_ap_ready)
);

real_matmul_dataflow_in_loop_CallBlockMatmul_1_MatB_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatB_BRAM_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_address0),
    .i_ce0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_ce0),
    .i_we0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_we0),
    .i_d0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_d0),
    .i_q0(MatB_BRAM_2_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(MatB_BRAM_2_i_q1),
    .t_address0(PerformMatrixCalculation_U0_MatB_BRAM_0_address0),
    .t_ce0(PerformMatrixCalculation_U0_MatB_BRAM_0_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(MatB_BRAM_2_t_q0),
    .t_address1(PerformMatrixCalculation_U0_MatB_BRAM_0_address1),
    .t_ce1(PerformMatrixCalculation_U0_MatB_BRAM_0_ce1),
    .t_q1(MatB_BRAM_2_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(MatB_BRAM_2_i_full_n),
    .i_write(ap_channel_done_MatB_BRAM_2),
    .t_empty_n(MatB_BRAM_2_t_empty_n),
    .t_read(PerformMatrixCalculation_U0_ap_ready)
);

real_matmul_dataflow_in_loop_CallBlockMatmul_1_MatB_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatA_BRAM_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_address0),
    .i_ce0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_ce0),
    .i_we0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_we0),
    .i_d0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_d0),
    .i_q0(MatA_BRAM_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(MatA_BRAM_i_q1),
    .t_address0(PerformMatrixCalculation_U0_MatA_BRAM_3_address0),
    .t_ce0(PerformMatrixCalculation_U0_MatA_BRAM_3_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(MatA_BRAM_t_q0),
    .t_address1(PerformMatrixCalculation_U0_MatA_BRAM_3_address1),
    .t_ce1(PerformMatrixCalculation_U0_MatA_BRAM_3_ce1),
    .t_q1(MatA_BRAM_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(MatA_BRAM_i_full_n),
    .i_write(ap_channel_done_MatA_BRAM),
    .t_empty_n(MatA_BRAM_t_empty_n),
    .t_read(PerformMatrixCalculation_U0_ap_ready)
);

real_matmul_dataflow_in_loop_CallBlockMatmul_1_MatB_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatA_BRAM_1_27_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_address0),
    .i_ce0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_ce0),
    .i_we0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_we0),
    .i_d0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_d0),
    .i_q0(MatA_BRAM_1_27_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(MatA_BRAM_1_27_i_q1),
    .t_address0(PerformMatrixCalculation_U0_MatA_BRAM_2_address0),
    .t_ce0(PerformMatrixCalculation_U0_MatA_BRAM_2_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(MatA_BRAM_1_27_t_q0),
    .t_address1(PerformMatrixCalculation_U0_MatA_BRAM_2_address1),
    .t_ce1(PerformMatrixCalculation_U0_MatA_BRAM_2_ce1),
    .t_q1(MatA_BRAM_1_27_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(MatA_BRAM_1_27_i_full_n),
    .i_write(ap_channel_done_MatA_BRAM_1_27),
    .t_empty_n(MatA_BRAM_1_27_t_empty_n),
    .t_read(PerformMatrixCalculation_U0_ap_ready)
);

real_matmul_dataflow_in_loop_CallBlockMatmul_1_MatB_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatA_BRAM_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_address0),
    .i_ce0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_ce0),
    .i_we0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_we0),
    .i_d0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_d0),
    .i_q0(MatA_BRAM_1_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(MatA_BRAM_1_i_q1),
    .t_address0(PerformMatrixCalculation_U0_MatA_BRAM_1_address0),
    .t_ce0(PerformMatrixCalculation_U0_MatA_BRAM_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(MatA_BRAM_1_t_q0),
    .t_address1(PerformMatrixCalculation_U0_MatA_BRAM_1_address1),
    .t_ce1(PerformMatrixCalculation_U0_MatA_BRAM_1_ce1),
    .t_q1(MatA_BRAM_1_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(MatA_BRAM_1_i_full_n),
    .i_write(ap_channel_done_MatA_BRAM_1),
    .t_empty_n(MatA_BRAM_1_t_empty_n),
    .t_read(PerformMatrixCalculation_U0_ap_ready)
);

real_matmul_dataflow_in_loop_CallBlockMatmul_1_MatB_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatA_BRAM_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_address0),
    .i_ce0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_ce0),
    .i_we0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_we0),
    .i_d0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_d0),
    .i_q0(MatA_BRAM_2_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(MatA_BRAM_2_i_q1),
    .t_address0(PerformMatrixCalculation_U0_MatA_BRAM_0_address0),
    .t_ce0(PerformMatrixCalculation_U0_MatA_BRAM_0_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(MatA_BRAM_2_t_q0),
    .t_address1(PerformMatrixCalculation_U0_MatA_BRAM_0_address1),
    .t_ce1(PerformMatrixCalculation_U0_MatA_BRAM_0_ce1),
    .t_q1(MatA_BRAM_2_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(MatA_BRAM_2_i_full_n),
    .i_write(ap_channel_done_MatA_BRAM_2),
    .t_empty_n(MatA_BRAM_2_t_empty_n),
    .t_read(PerformMatrixCalculation_U0_ap_ready)
);

real_matmul_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .MatC_DRAM(MatC_DRAM),
    .MatC_DRAM_c_din(entry_proc_U0_MatC_DRAM_c_din),
    .MatC_DRAM_c_num_data_valid(MatC_DRAM_c_num_data_valid),
    .MatC_DRAM_c_fifo_cap(MatC_DRAM_c_fifo_cap),
    .MatC_DRAM_c_full_n(MatC_DRAM_c_full_n),
    .MatC_DRAM_c_write(entry_proc_U0_MatC_DRAM_c_write)
);

real_matmul_LoadMatricesFromDRAMToBRAM LoadMatricesFromDRAMToBRAM_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(LoadMatricesFromDRAMToBRAM_U0_ap_start),
    .ap_done(LoadMatricesFromDRAMToBRAM_U0_ap_done),
    .ap_continue(LoadMatricesFromDRAMToBRAM_U0_ap_continue),
    .ap_idle(LoadMatricesFromDRAMToBRAM_U0_ap_idle),
    .ap_ready(LoadMatricesFromDRAMToBRAM_U0_ap_ready),
    .MatA_BRAM_0_address0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_address0),
    .MatA_BRAM_0_ce0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_ce0),
    .MatA_BRAM_0_we0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_we0),
    .MatA_BRAM_0_d0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_d0),
    .MatA_BRAM_1_address0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_address0),
    .MatA_BRAM_1_ce0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_ce0),
    .MatA_BRAM_1_we0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_we0),
    .MatA_BRAM_1_d0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_d0),
    .MatA_BRAM_2_address0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_address0),
    .MatA_BRAM_2_ce0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_ce0),
    .MatA_BRAM_2_we0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_we0),
    .MatA_BRAM_2_d0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_d0),
    .MatA_BRAM_3_address0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_address0),
    .MatA_BRAM_3_ce0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_ce0),
    .MatA_BRAM_3_we0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_we0),
    .MatA_BRAM_3_d0(LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_d0),
    .m_axi_MatA_AWVALID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWVALID),
    .m_axi_MatA_AWREADY(1'b0),
    .m_axi_MatA_AWADDR(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWADDR),
    .m_axi_MatA_AWID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWID),
    .m_axi_MatA_AWLEN(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWLEN),
    .m_axi_MatA_AWSIZE(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWSIZE),
    .m_axi_MatA_AWBURST(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWBURST),
    .m_axi_MatA_AWLOCK(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWLOCK),
    .m_axi_MatA_AWCACHE(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWCACHE),
    .m_axi_MatA_AWPROT(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWPROT),
    .m_axi_MatA_AWQOS(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWQOS),
    .m_axi_MatA_AWREGION(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWREGION),
    .m_axi_MatA_AWUSER(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_AWUSER),
    .m_axi_MatA_WVALID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WVALID),
    .m_axi_MatA_WREADY(1'b0),
    .m_axi_MatA_WDATA(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WDATA),
    .m_axi_MatA_WSTRB(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WSTRB),
    .m_axi_MatA_WLAST(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WLAST),
    .m_axi_MatA_WID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WID),
    .m_axi_MatA_WUSER(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_WUSER),
    .m_axi_MatA_ARVALID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARVALID),
    .m_axi_MatA_ARREADY(m_axi_MatA_ARREADY),
    .m_axi_MatA_ARADDR(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARADDR),
    .m_axi_MatA_ARID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARID),
    .m_axi_MatA_ARLEN(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARLEN),
    .m_axi_MatA_ARSIZE(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARSIZE),
    .m_axi_MatA_ARBURST(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARBURST),
    .m_axi_MatA_ARLOCK(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARLOCK),
    .m_axi_MatA_ARCACHE(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARCACHE),
    .m_axi_MatA_ARPROT(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARPROT),
    .m_axi_MatA_ARQOS(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARQOS),
    .m_axi_MatA_ARREGION(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARREGION),
    .m_axi_MatA_ARUSER(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARUSER),
    .m_axi_MatA_RVALID(m_axi_MatA_RVALID),
    .m_axi_MatA_RREADY(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_RREADY),
    .m_axi_MatA_RDATA(m_axi_MatA_RDATA),
    .m_axi_MatA_RLAST(m_axi_MatA_RLAST),
    .m_axi_MatA_RID(m_axi_MatA_RID),
    .m_axi_MatA_RFIFONUM(m_axi_MatA_RFIFONUM),
    .m_axi_MatA_RUSER(m_axi_MatA_RUSER),
    .m_axi_MatA_RRESP(m_axi_MatA_RRESP),
    .m_axi_MatA_BVALID(1'b0),
    .m_axi_MatA_BREADY(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_BREADY),
    .m_axi_MatA_BRESP(2'd0),
    .m_axi_MatA_BID(1'd0),
    .m_axi_MatA_BUSER(1'd0),
    .MatA_DRAM(MatA_DRAM),
    .MatB_BRAM_0_address0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_address0),
    .MatB_BRAM_0_ce0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_ce0),
    .MatB_BRAM_0_we0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_we0),
    .MatB_BRAM_0_d0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_d0),
    .MatB_BRAM_1_address0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_address0),
    .MatB_BRAM_1_ce0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_ce0),
    .MatB_BRAM_1_we0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_we0),
    .MatB_BRAM_1_d0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_d0),
    .MatB_BRAM_2_address0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_address0),
    .MatB_BRAM_2_ce0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_ce0),
    .MatB_BRAM_2_we0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_we0),
    .MatB_BRAM_2_d0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_d0),
    .MatB_BRAM_3_address0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_address0),
    .MatB_BRAM_3_ce0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_ce0),
    .MatB_BRAM_3_we0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_we0),
    .MatB_BRAM_3_d0(LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_d0),
    .m_axi_MatB_AWVALID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWVALID),
    .m_axi_MatB_AWREADY(1'b0),
    .m_axi_MatB_AWADDR(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWADDR),
    .m_axi_MatB_AWID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWID),
    .m_axi_MatB_AWLEN(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWLEN),
    .m_axi_MatB_AWSIZE(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWSIZE),
    .m_axi_MatB_AWBURST(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWBURST),
    .m_axi_MatB_AWLOCK(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWLOCK),
    .m_axi_MatB_AWCACHE(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWCACHE),
    .m_axi_MatB_AWPROT(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWPROT),
    .m_axi_MatB_AWQOS(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWQOS),
    .m_axi_MatB_AWREGION(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWREGION),
    .m_axi_MatB_AWUSER(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_AWUSER),
    .m_axi_MatB_WVALID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WVALID),
    .m_axi_MatB_WREADY(1'b0),
    .m_axi_MatB_WDATA(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WDATA),
    .m_axi_MatB_WSTRB(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WSTRB),
    .m_axi_MatB_WLAST(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WLAST),
    .m_axi_MatB_WID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WID),
    .m_axi_MatB_WUSER(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_WUSER),
    .m_axi_MatB_ARVALID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARVALID),
    .m_axi_MatB_ARREADY(m_axi_MatB_ARREADY),
    .m_axi_MatB_ARADDR(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARADDR),
    .m_axi_MatB_ARID(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARID),
    .m_axi_MatB_ARLEN(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARLEN),
    .m_axi_MatB_ARSIZE(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARSIZE),
    .m_axi_MatB_ARBURST(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARBURST),
    .m_axi_MatB_ARLOCK(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARLOCK),
    .m_axi_MatB_ARCACHE(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARCACHE),
    .m_axi_MatB_ARPROT(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARPROT),
    .m_axi_MatB_ARQOS(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARQOS),
    .m_axi_MatB_ARREGION(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARREGION),
    .m_axi_MatB_ARUSER(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARUSER),
    .m_axi_MatB_RVALID(m_axi_MatB_RVALID),
    .m_axi_MatB_RREADY(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_RREADY),
    .m_axi_MatB_RDATA(m_axi_MatB_RDATA),
    .m_axi_MatB_RLAST(m_axi_MatB_RLAST),
    .m_axi_MatB_RID(m_axi_MatB_RID),
    .m_axi_MatB_RFIFONUM(m_axi_MatB_RFIFONUM),
    .m_axi_MatB_RUSER(m_axi_MatB_RUSER),
    .m_axi_MatB_RRESP(m_axi_MatB_RRESP),
    .m_axi_MatB_BVALID(1'b0),
    .m_axi_MatB_BREADY(LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_BREADY),
    .m_axi_MatB_BRESP(2'd0),
    .m_axi_MatB_BID(1'd0),
    .m_axi_MatB_BUSER(1'd0),
    .MatB_DRAM(MatB_DRAM),
    .counter(counter_0),
    .ap_return(LoadMatricesFromDRAMToBRAM_U0_ap_return)
);

real_matmul_PerformMatrixCalculation PerformMatrixCalculation_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(PerformMatrixCalculation_U0_ap_start),
    .ap_done(PerformMatrixCalculation_U0_ap_done),
    .ap_continue(PerformMatrixCalculation_U0_ap_continue),
    .ap_idle(PerformMatrixCalculation_U0_ap_idle),
    .ap_ready(PerformMatrixCalculation_U0_ap_ready),
    .MatA_BRAM_0_address0(PerformMatrixCalculation_U0_MatA_BRAM_0_address0),
    .MatA_BRAM_0_ce0(PerformMatrixCalculation_U0_MatA_BRAM_0_ce0),
    .MatA_BRAM_0_q0(MatA_BRAM_2_t_q0),
    .MatA_BRAM_0_address1(PerformMatrixCalculation_U0_MatA_BRAM_0_address1),
    .MatA_BRAM_0_ce1(PerformMatrixCalculation_U0_MatA_BRAM_0_ce1),
    .MatA_BRAM_0_q1(MatA_BRAM_2_t_q1),
    .MatA_BRAM_1_address0(PerformMatrixCalculation_U0_MatA_BRAM_1_address0),
    .MatA_BRAM_1_ce0(PerformMatrixCalculation_U0_MatA_BRAM_1_ce0),
    .MatA_BRAM_1_q0(MatA_BRAM_1_t_q0),
    .MatA_BRAM_1_address1(PerformMatrixCalculation_U0_MatA_BRAM_1_address1),
    .MatA_BRAM_1_ce1(PerformMatrixCalculation_U0_MatA_BRAM_1_ce1),
    .MatA_BRAM_1_q1(MatA_BRAM_1_t_q1),
    .MatA_BRAM_2_address0(PerformMatrixCalculation_U0_MatA_BRAM_2_address0),
    .MatA_BRAM_2_ce0(PerformMatrixCalculation_U0_MatA_BRAM_2_ce0),
    .MatA_BRAM_2_q0(MatA_BRAM_1_27_t_q0),
    .MatA_BRAM_2_address1(PerformMatrixCalculation_U0_MatA_BRAM_2_address1),
    .MatA_BRAM_2_ce1(PerformMatrixCalculation_U0_MatA_BRAM_2_ce1),
    .MatA_BRAM_2_q1(MatA_BRAM_1_27_t_q1),
    .MatA_BRAM_3_address0(PerformMatrixCalculation_U0_MatA_BRAM_3_address0),
    .MatA_BRAM_3_ce0(PerformMatrixCalculation_U0_MatA_BRAM_3_ce0),
    .MatA_BRAM_3_q0(MatA_BRAM_t_q0),
    .MatA_BRAM_3_address1(PerformMatrixCalculation_U0_MatA_BRAM_3_address1),
    .MatA_BRAM_3_ce1(PerformMatrixCalculation_U0_MatA_BRAM_3_ce1),
    .MatA_BRAM_3_q1(MatA_BRAM_t_q1),
    .MatB_BRAM_0_address0(PerformMatrixCalculation_U0_MatB_BRAM_0_address0),
    .MatB_BRAM_0_ce0(PerformMatrixCalculation_U0_MatB_BRAM_0_ce0),
    .MatB_BRAM_0_q0(MatB_BRAM_2_t_q0),
    .MatB_BRAM_0_address1(PerformMatrixCalculation_U0_MatB_BRAM_0_address1),
    .MatB_BRAM_0_ce1(PerformMatrixCalculation_U0_MatB_BRAM_0_ce1),
    .MatB_BRAM_0_q1(MatB_BRAM_2_t_q1),
    .MatB_BRAM_1_address0(PerformMatrixCalculation_U0_MatB_BRAM_1_address0),
    .MatB_BRAM_1_ce0(PerformMatrixCalculation_U0_MatB_BRAM_1_ce0),
    .MatB_BRAM_1_q0(MatB_BRAM_1_t_q0),
    .MatB_BRAM_1_address1(PerformMatrixCalculation_U0_MatB_BRAM_1_address1),
    .MatB_BRAM_1_ce1(PerformMatrixCalculation_U0_MatB_BRAM_1_ce1),
    .MatB_BRAM_1_q1(MatB_BRAM_1_t_q1),
    .MatB_BRAM_2_address0(PerformMatrixCalculation_U0_MatB_BRAM_2_address0),
    .MatB_BRAM_2_ce0(PerformMatrixCalculation_U0_MatB_BRAM_2_ce0),
    .MatB_BRAM_2_q0(MatB_BRAM_1_26_t_q0),
    .MatB_BRAM_2_address1(PerformMatrixCalculation_U0_MatB_BRAM_2_address1),
    .MatB_BRAM_2_ce1(PerformMatrixCalculation_U0_MatB_BRAM_2_ce1),
    .MatB_BRAM_2_q1(MatB_BRAM_1_26_t_q1),
    .MatB_BRAM_3_address0(PerformMatrixCalculation_U0_MatB_BRAM_3_address0),
    .MatB_BRAM_3_ce0(PerformMatrixCalculation_U0_MatB_BRAM_3_ce0),
    .MatB_BRAM_3_q0(MatB_BRAM_t_q0),
    .MatB_BRAM_3_address1(PerformMatrixCalculation_U0_MatB_BRAM_3_address1),
    .MatB_BRAM_3_ce1(PerformMatrixCalculation_U0_MatB_BRAM_3_ce1),
    .MatB_BRAM_3_q1(MatB_BRAM_t_q1),
    .MatC_BRAM_address0(PerformMatrixCalculation_U0_MatC_BRAM_address0),
    .MatC_BRAM_ce0(PerformMatrixCalculation_U0_MatC_BRAM_ce0),
    .MatC_BRAM_we0(PerformMatrixCalculation_U0_MatC_BRAM_we0),
    .MatC_BRAM_d0(PerformMatrixCalculation_U0_MatC_BRAM_d0)
);

real_matmul_LoadMatricesFromBRAMToDRAM LoadMatricesFromBRAMToDRAM_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(LoadMatricesFromBRAMToDRAM_U0_ap_start),
    .ap_done(LoadMatricesFromBRAMToDRAM_U0_ap_done),
    .ap_continue(LoadMatricesFromBRAMToDRAM_U0_ap_continue),
    .ap_idle(LoadMatricesFromBRAMToDRAM_U0_ap_idle),
    .ap_ready(LoadMatricesFromBRAMToDRAM_U0_ap_ready),
    .MatC_BRAM_address0(LoadMatricesFromBRAMToDRAM_U0_MatC_BRAM_address0),
    .MatC_BRAM_ce0(LoadMatricesFromBRAMToDRAM_U0_MatC_BRAM_ce0),
    .MatC_BRAM_q0(MatC_BRAM_t_q0),
    .m_axi_MatC_AWVALID(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWVALID),
    .m_axi_MatC_AWREADY(m_axi_MatC_AWREADY),
    .m_axi_MatC_AWADDR(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWADDR),
    .m_axi_MatC_AWID(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWID),
    .m_axi_MatC_AWLEN(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWLEN),
    .m_axi_MatC_AWSIZE(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWSIZE),
    .m_axi_MatC_AWBURST(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWBURST),
    .m_axi_MatC_AWLOCK(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWLOCK),
    .m_axi_MatC_AWCACHE(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWCACHE),
    .m_axi_MatC_AWPROT(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWPROT),
    .m_axi_MatC_AWQOS(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWQOS),
    .m_axi_MatC_AWREGION(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWREGION),
    .m_axi_MatC_AWUSER(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWUSER),
    .m_axi_MatC_WVALID(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WVALID),
    .m_axi_MatC_WREADY(m_axi_MatC_WREADY),
    .m_axi_MatC_WDATA(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WDATA),
    .m_axi_MatC_WSTRB(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WSTRB),
    .m_axi_MatC_WLAST(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WLAST),
    .m_axi_MatC_WID(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WID),
    .m_axi_MatC_WUSER(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WUSER),
    .m_axi_MatC_ARVALID(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARVALID),
    .m_axi_MatC_ARREADY(1'b0),
    .m_axi_MatC_ARADDR(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARADDR),
    .m_axi_MatC_ARID(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARID),
    .m_axi_MatC_ARLEN(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARLEN),
    .m_axi_MatC_ARSIZE(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARSIZE),
    .m_axi_MatC_ARBURST(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARBURST),
    .m_axi_MatC_ARLOCK(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARLOCK),
    .m_axi_MatC_ARCACHE(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARCACHE),
    .m_axi_MatC_ARPROT(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARPROT),
    .m_axi_MatC_ARQOS(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARQOS),
    .m_axi_MatC_ARREGION(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARREGION),
    .m_axi_MatC_ARUSER(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_ARUSER),
    .m_axi_MatC_RVALID(1'b0),
    .m_axi_MatC_RREADY(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_RREADY),
    .m_axi_MatC_RDATA(16'd0),
    .m_axi_MatC_RLAST(1'b0),
    .m_axi_MatC_RID(1'd0),
    .m_axi_MatC_RFIFONUM(10'd0),
    .m_axi_MatC_RUSER(1'd0),
    .m_axi_MatC_RRESP(2'd0),
    .m_axi_MatC_BVALID(m_axi_MatC_BVALID),
    .m_axi_MatC_BREADY(LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_BREADY),
    .m_axi_MatC_BRESP(m_axi_MatC_BRESP),
    .m_axi_MatC_BID(m_axi_MatC_BID),
    .m_axi_MatC_BUSER(m_axi_MatC_BUSER),
    .MatC_DRAM_dout(MatC_DRAM_c_dout),
    .MatC_DRAM_num_data_valid(MatC_DRAM_c_num_data_valid),
    .MatC_DRAM_fifo_cap(MatC_DRAM_c_fifo_cap),
    .MatC_DRAM_empty_n(MatC_DRAM_c_empty_n),
    .MatC_DRAM_read(LoadMatricesFromBRAMToDRAM_U0_MatC_DRAM_read),
    .p_read(counter_0_c_channel_dout)
);

real_matmul_fifo_w64_d4_S MatC_DRAM_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_MatC_DRAM_c_din),
    .if_full_n(MatC_DRAM_c_full_n),
    .if_write(entry_proc_U0_MatC_DRAM_c_write),
    .if_dout(MatC_DRAM_c_dout),
    .if_num_data_valid(MatC_DRAM_c_num_data_valid),
    .if_fifo_cap(MatC_DRAM_c_fifo_cap),
    .if_empty_n(MatC_DRAM_c_empty_n),
    .if_read(LoadMatricesFromBRAMToDRAM_U0_MatC_DRAM_read)
);

real_matmul_fifo_w11_d3_S counter_0_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(LoadMatricesFromDRAMToBRAM_U0_ap_return),
    .if_full_n(counter_0_c_channel_full_n),
    .if_write(ap_channel_done_counter_0_c_channel),
    .if_dout(counter_0_c_channel_dout),
    .if_num_data_valid(counter_0_c_channel_num_data_valid),
    .if_fifo_cap(counter_0_c_channel_fifo_cap),
    .if_empty_n(counter_0_c_channel_empty_n),
    .if_read(LoadMatricesFromBRAMToDRAM_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_LoadMatricesFromDRAMToBRAM_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_LoadMatricesFromDRAMToBRAM_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_LoadMatricesFromDRAMToBRAM_U0_ap_ready <= ap_sync_LoadMatricesFromDRAMToBRAM_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_MatA_BRAM <= 1'b0;
    end else begin
        if (((LoadMatricesFromDRAMToBRAM_U0_ap_done & LoadMatricesFromDRAMToBRAM_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_MatA_BRAM <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_MatA_BRAM <= ap_sync_channel_write_MatA_BRAM;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_MatA_BRAM_1 <= 1'b0;
    end else begin
        if (((LoadMatricesFromDRAMToBRAM_U0_ap_done & LoadMatricesFromDRAMToBRAM_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_MatA_BRAM_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_MatA_BRAM_1 <= ap_sync_channel_write_MatA_BRAM_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_MatA_BRAM_1_27 <= 1'b0;
    end else begin
        if (((LoadMatricesFromDRAMToBRAM_U0_ap_done & LoadMatricesFromDRAMToBRAM_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_MatA_BRAM_1_27 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_MatA_BRAM_1_27 <= ap_sync_channel_write_MatA_BRAM_1_27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_MatA_BRAM_2 <= 1'b0;
    end else begin
        if (((LoadMatricesFromDRAMToBRAM_U0_ap_done & LoadMatricesFromDRAMToBRAM_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_MatA_BRAM_2 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_MatA_BRAM_2 <= ap_sync_channel_write_MatA_BRAM_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_MatB_BRAM <= 1'b0;
    end else begin
        if (((LoadMatricesFromDRAMToBRAM_U0_ap_done & LoadMatricesFromDRAMToBRAM_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_MatB_BRAM <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_MatB_BRAM <= ap_sync_channel_write_MatB_BRAM;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_MatB_BRAM_1 <= 1'b0;
    end else begin
        if (((LoadMatricesFromDRAMToBRAM_U0_ap_done & LoadMatricesFromDRAMToBRAM_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_MatB_BRAM_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_MatB_BRAM_1 <= ap_sync_channel_write_MatB_BRAM_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_MatB_BRAM_1_26 <= 1'b0;
    end else begin
        if (((LoadMatricesFromDRAMToBRAM_U0_ap_done & LoadMatricesFromDRAMToBRAM_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_MatB_BRAM_1_26 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_MatB_BRAM_1_26 <= ap_sync_channel_write_MatB_BRAM_1_26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_MatB_BRAM_2 <= 1'b0;
    end else begin
        if (((LoadMatricesFromDRAMToBRAM_U0_ap_done & LoadMatricesFromDRAMToBRAM_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_MatB_BRAM_2 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_MatB_BRAM_2 <= ap_sync_channel_write_MatB_BRAM_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_counter_0_c_channel <= 1'b0;
    end else begin
        if (((LoadMatricesFromDRAMToBRAM_U0_ap_done & LoadMatricesFromDRAMToBRAM_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_counter_0_c_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_counter_0_c_channel <= ap_sync_channel_write_counter_0_c_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign LoadMatricesFromBRAMToDRAM_U0_ap_continue = ap_continue;

assign LoadMatricesFromBRAMToDRAM_U0_ap_start = (counter_0_c_channel_empty_n & MatC_BRAM_t_empty_n);

assign LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_full_n = MatA_BRAM_2_i_full_n;

assign LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_full_n = MatA_BRAM_1_i_full_n;

assign LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_full_n = MatA_BRAM_1_27_i_full_n;

assign LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_full_n = MatA_BRAM_i_full_n;

assign LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_full_n = MatB_BRAM_2_i_full_n;

assign LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_full_n = MatB_BRAM_1_i_full_n;

assign LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_full_n = MatB_BRAM_1_26_i_full_n;

assign LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_full_n = MatB_BRAM_i_full_n;

assign LoadMatricesFromDRAMToBRAM_U0_ap_continue = (ap_sync_channel_write_counter_0_c_channel & ap_sync_channel_write_MatB_BRAM_2 & ap_sync_channel_write_MatB_BRAM_1_26 & ap_sync_channel_write_MatB_BRAM_1 & ap_sync_channel_write_MatB_BRAM & ap_sync_channel_write_MatA_BRAM_2 & ap_sync_channel_write_MatA_BRAM_1_27 & ap_sync_channel_write_MatA_BRAM_1 & ap_sync_channel_write_MatA_BRAM);

assign LoadMatricesFromDRAMToBRAM_U0_ap_start = ((ap_sync_reg_LoadMatricesFromDRAMToBRAM_U0_ap_ready ^ 1'b1) & ap_start);

assign PerformMatrixCalculation_U0_ap_continue = MatC_BRAM_i_full_n;

assign PerformMatrixCalculation_U0_ap_start = (MatB_BRAM_t_empty_n & MatB_BRAM_2_t_empty_n & MatB_BRAM_1_t_empty_n & MatB_BRAM_1_26_t_empty_n & MatA_BRAM_t_empty_n & MatA_BRAM_2_t_empty_n & MatA_BRAM_1_t_empty_n & MatA_BRAM_1_27_t_empty_n);

assign ap_channel_done_MatA_BRAM = ((ap_sync_reg_channel_write_MatA_BRAM ^ 1'b1) & LoadMatricesFromDRAMToBRAM_U0_ap_done);

assign ap_channel_done_MatA_BRAM_1 = ((ap_sync_reg_channel_write_MatA_BRAM_1 ^ 1'b1) & LoadMatricesFromDRAMToBRAM_U0_ap_done);

assign ap_channel_done_MatA_BRAM_1_27 = ((ap_sync_reg_channel_write_MatA_BRAM_1_27 ^ 1'b1) & LoadMatricesFromDRAMToBRAM_U0_ap_done);

assign ap_channel_done_MatA_BRAM_2 = ((ap_sync_reg_channel_write_MatA_BRAM_2 ^ 1'b1) & LoadMatricesFromDRAMToBRAM_U0_ap_done);

assign ap_channel_done_MatB_BRAM = ((ap_sync_reg_channel_write_MatB_BRAM ^ 1'b1) & LoadMatricesFromDRAMToBRAM_U0_ap_done);

assign ap_channel_done_MatB_BRAM_1 = ((ap_sync_reg_channel_write_MatB_BRAM_1 ^ 1'b1) & LoadMatricesFromDRAMToBRAM_U0_ap_done);

assign ap_channel_done_MatB_BRAM_1_26 = ((ap_sync_reg_channel_write_MatB_BRAM_1_26 ^ 1'b1) & LoadMatricesFromDRAMToBRAM_U0_ap_done);

assign ap_channel_done_MatB_BRAM_2 = ((ap_sync_reg_channel_write_MatB_BRAM_2 ^ 1'b1) & LoadMatricesFromDRAMToBRAM_U0_ap_done);

assign ap_channel_done_counter_0_c_channel = ((ap_sync_reg_channel_write_counter_0_c_channel ^ 1'b1) & LoadMatricesFromDRAMToBRAM_U0_ap_done);

assign ap_done = LoadMatricesFromBRAMToDRAM_U0_ap_done;

assign ap_idle = ((counter_0_c_channel_empty_n ^ 1'b1) & (1'b1 ^ MatC_BRAM_t_empty_n) & (1'b1 ^ MatB_BRAM_t_empty_n) & (1'b1 ^ MatB_BRAM_1_26_t_empty_n) & (1'b1 ^ MatB_BRAM_1_t_empty_n) & (1'b1 ^ MatB_BRAM_2_t_empty_n) & (1'b1 ^ MatA_BRAM_t_empty_n) & (1'b1 ^ MatA_BRAM_1_27_t_empty_n) & (1'b1 ^ MatA_BRAM_1_t_empty_n) & (1'b1 ^ MatA_BRAM_2_t_empty_n) & entry_proc_U0_ap_idle & PerformMatrixCalculation_U0_ap_idle & LoadMatricesFromDRAMToBRAM_U0_ap_idle & LoadMatricesFromBRAMToDRAM_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_LoadMatricesFromDRAMToBRAM_U0_ap_ready = (ap_sync_reg_LoadMatricesFromDRAMToBRAM_U0_ap_ready | LoadMatricesFromDRAMToBRAM_U0_ap_ready);

assign ap_sync_channel_write_MatA_BRAM = ((ap_channel_done_MatA_BRAM & LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_3_full_n) | ap_sync_reg_channel_write_MatA_BRAM);

assign ap_sync_channel_write_MatA_BRAM_1 = ((ap_channel_done_MatA_BRAM_1 & LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_1_full_n) | ap_sync_reg_channel_write_MatA_BRAM_1);

assign ap_sync_channel_write_MatA_BRAM_1_27 = ((ap_channel_done_MatA_BRAM_1_27 & LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_2_full_n) | ap_sync_reg_channel_write_MatA_BRAM_1_27);

assign ap_sync_channel_write_MatA_BRAM_2 = ((ap_channel_done_MatA_BRAM_2 & LoadMatricesFromDRAMToBRAM_U0_MatA_BRAM_0_full_n) | ap_sync_reg_channel_write_MatA_BRAM_2);

assign ap_sync_channel_write_MatB_BRAM = ((ap_channel_done_MatB_BRAM & LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_3_full_n) | ap_sync_reg_channel_write_MatB_BRAM);

assign ap_sync_channel_write_MatB_BRAM_1 = ((ap_channel_done_MatB_BRAM_1 & LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_1_full_n) | ap_sync_reg_channel_write_MatB_BRAM_1);

assign ap_sync_channel_write_MatB_BRAM_1_26 = ((ap_channel_done_MatB_BRAM_1_26 & LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_2_full_n) | ap_sync_reg_channel_write_MatB_BRAM_1_26);

assign ap_sync_channel_write_MatB_BRAM_2 = ((ap_channel_done_MatB_BRAM_2 & LoadMatricesFromDRAMToBRAM_U0_MatB_BRAM_0_full_n) | ap_sync_reg_channel_write_MatB_BRAM_2);

assign ap_sync_channel_write_counter_0_c_channel = ((counter_0_c_channel_full_n & ap_channel_done_counter_0_c_channel) | ap_sync_reg_channel_write_counter_0_c_channel);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_LoadMatricesFromDRAMToBRAM_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign m_axi_MatA_ARADDR = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARADDR;

assign m_axi_MatA_ARBURST = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARBURST;

assign m_axi_MatA_ARCACHE = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARCACHE;

assign m_axi_MatA_ARID = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARID;

assign m_axi_MatA_ARLEN = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARLEN;

assign m_axi_MatA_ARLOCK = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARLOCK;

assign m_axi_MatA_ARPROT = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARPROT;

assign m_axi_MatA_ARQOS = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARQOS;

assign m_axi_MatA_ARREGION = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARREGION;

assign m_axi_MatA_ARSIZE = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARSIZE;

assign m_axi_MatA_ARUSER = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARUSER;

assign m_axi_MatA_ARVALID = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_ARVALID;

assign m_axi_MatA_AWADDR = 64'd0;

assign m_axi_MatA_AWBURST = 2'd0;

assign m_axi_MatA_AWCACHE = 4'd0;

assign m_axi_MatA_AWID = 1'd0;

assign m_axi_MatA_AWLEN = 32'd0;

assign m_axi_MatA_AWLOCK = 2'd0;

assign m_axi_MatA_AWPROT = 3'd0;

assign m_axi_MatA_AWQOS = 4'd0;

assign m_axi_MatA_AWREGION = 4'd0;

assign m_axi_MatA_AWSIZE = 3'd0;

assign m_axi_MatA_AWUSER = 1'd0;

assign m_axi_MatA_AWVALID = 1'b0;

assign m_axi_MatA_BREADY = 1'b0;

assign m_axi_MatA_RREADY = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatA_RREADY;

assign m_axi_MatA_WDATA = 16'd0;

assign m_axi_MatA_WID = 1'd0;

assign m_axi_MatA_WLAST = 1'b0;

assign m_axi_MatA_WSTRB = 2'd0;

assign m_axi_MatA_WUSER = 1'd0;

assign m_axi_MatA_WVALID = 1'b0;

assign m_axi_MatB_ARADDR = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARADDR;

assign m_axi_MatB_ARBURST = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARBURST;

assign m_axi_MatB_ARCACHE = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARCACHE;

assign m_axi_MatB_ARID = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARID;

assign m_axi_MatB_ARLEN = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARLEN;

assign m_axi_MatB_ARLOCK = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARLOCK;

assign m_axi_MatB_ARPROT = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARPROT;

assign m_axi_MatB_ARQOS = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARQOS;

assign m_axi_MatB_ARREGION = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARREGION;

assign m_axi_MatB_ARSIZE = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARSIZE;

assign m_axi_MatB_ARUSER = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARUSER;

assign m_axi_MatB_ARVALID = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_ARVALID;

assign m_axi_MatB_AWADDR = 64'd0;

assign m_axi_MatB_AWBURST = 2'd0;

assign m_axi_MatB_AWCACHE = 4'd0;

assign m_axi_MatB_AWID = 1'd0;

assign m_axi_MatB_AWLEN = 32'd0;

assign m_axi_MatB_AWLOCK = 2'd0;

assign m_axi_MatB_AWPROT = 3'd0;

assign m_axi_MatB_AWQOS = 4'd0;

assign m_axi_MatB_AWREGION = 4'd0;

assign m_axi_MatB_AWSIZE = 3'd0;

assign m_axi_MatB_AWUSER = 1'd0;

assign m_axi_MatB_AWVALID = 1'b0;

assign m_axi_MatB_BREADY = 1'b0;

assign m_axi_MatB_RREADY = LoadMatricesFromDRAMToBRAM_U0_m_axi_MatB_RREADY;

assign m_axi_MatB_WDATA = 16'd0;

assign m_axi_MatB_WID = 1'd0;

assign m_axi_MatB_WLAST = 1'b0;

assign m_axi_MatB_WSTRB = 2'd0;

assign m_axi_MatB_WUSER = 1'd0;

assign m_axi_MatB_WVALID = 1'b0;

assign m_axi_MatC_ARADDR = 64'd0;

assign m_axi_MatC_ARBURST = 2'd0;

assign m_axi_MatC_ARCACHE = 4'd0;

assign m_axi_MatC_ARID = 1'd0;

assign m_axi_MatC_ARLEN = 32'd0;

assign m_axi_MatC_ARLOCK = 2'd0;

assign m_axi_MatC_ARPROT = 3'd0;

assign m_axi_MatC_ARQOS = 4'd0;

assign m_axi_MatC_ARREGION = 4'd0;

assign m_axi_MatC_ARSIZE = 3'd0;

assign m_axi_MatC_ARUSER = 1'd0;

assign m_axi_MatC_ARVALID = 1'b0;

assign m_axi_MatC_AWADDR = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWADDR;

assign m_axi_MatC_AWBURST = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWBURST;

assign m_axi_MatC_AWCACHE = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWCACHE;

assign m_axi_MatC_AWID = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWID;

assign m_axi_MatC_AWLEN = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWLEN;

assign m_axi_MatC_AWLOCK = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWLOCK;

assign m_axi_MatC_AWPROT = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWPROT;

assign m_axi_MatC_AWQOS = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWQOS;

assign m_axi_MatC_AWREGION = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWREGION;

assign m_axi_MatC_AWSIZE = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWSIZE;

assign m_axi_MatC_AWUSER = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWUSER;

assign m_axi_MatC_AWVALID = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_AWVALID;

assign m_axi_MatC_BREADY = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_BREADY;

assign m_axi_MatC_RREADY = 1'b0;

assign m_axi_MatC_WDATA = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WDATA;

assign m_axi_MatC_WID = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WID;

assign m_axi_MatC_WLAST = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WLAST;

assign m_axi_MatC_WSTRB = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WSTRB;

assign m_axi_MatC_WUSER = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WUSER;

assign m_axi_MatC_WVALID = LoadMatricesFromBRAMToDRAM_U0_m_axi_MatC_WVALID;

endmodule //real_matmul_dataflow_in_loop_CallBlockMatmul_1
