# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Personal/FPGA/FPGA_ECE8893/2023_Spring/Lab1/PartA/MatrixMultiplier/MatrixMultiplier.srcs/sources_1/bd/matmul/ip/matmul_processing_system7_0_0/matmul_processing_system7_0_0.xci
# IP: The module: 'matmul_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Personal/FPGA/FPGA_ECE8893/2023_Spring/Lab1/PartA/MatrixMultiplier/MatrixMultiplier.gen/sources_1/bd/matmul/ip/matmul_processing_system7_0_0/matmul_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmul_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Personal/FPGA/FPGA_ECE8893/2023_Spring/Lab1/PartA/MatrixMultiplier/MatrixMultiplier.srcs/sources_1/bd/matmul/ip/matmul_processing_system7_0_0/matmul_processing_system7_0_0.xci
# IP: The module: 'matmul_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Personal/FPGA/FPGA_ECE8893/2023_Spring/Lab1/PartA/MatrixMultiplier/MatrixMultiplier.gen/sources_1/bd/matmul/ip/matmul_processing_system7_0_0/matmul_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmul_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
