# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Personal/FPGA/FPGA_ECE8893/2023_Spring/Lab1/PartA/MatrixMultiplier/MatrixMultiplier.srcs/sources_1/bd/matmul/ip/matmul_auto_us_1/matmul_auto_us_1.xci
# IP: The module: 'matmul_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Personal/FPGA/FPGA_ECE8893/2023_Spring/Lab1/PartA/MatrixMultiplier/MatrixMultiplier.gen/sources_1/bd/matmul/ip/matmul_auto_us_1/matmul_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmul_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Personal/FPGA/FPGA_ECE8893/2023_Spring/Lab1/PartA/MatrixMultiplier/MatrixMultiplier.gen/sources_1/bd/matmul/ip/matmul_auto_us_1/matmul_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmul_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Personal/FPGA/FPGA_ECE8893/2023_Spring/Lab1/PartA/MatrixMultiplier/MatrixMultiplier.srcs/sources_1/bd/matmul/ip/matmul_auto_us_1/matmul_auto_us_1.xci
# IP: The module: 'matmul_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Personal/FPGA/FPGA_ECE8893/2023_Spring/Lab1/PartA/MatrixMultiplier/MatrixMultiplier.gen/sources_1/bd/matmul/ip/matmul_auto_us_1/matmul_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmul_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Personal/FPGA/FPGA_ECE8893/2023_Spring/Lab1/PartA/MatrixMultiplier/MatrixMultiplier.gen/sources_1/bd/matmul/ip/matmul_auto_us_1/matmul_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmul_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
