// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="real_matmul_real_matmul,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=1702501,HLS_SYN_TPT=none,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=26707,HLS_SYN_LUT=22737,HLS_VERSION=2023_1}" *)

module real_matmul (
        ap_clk,
        ap_rst_n,
        m_axi_mem_AWVALID,
        m_axi_mem_AWREADY,
        m_axi_mem_AWADDR,
        m_axi_mem_AWID,
        m_axi_mem_AWLEN,
        m_axi_mem_AWSIZE,
        m_axi_mem_AWBURST,
        m_axi_mem_AWLOCK,
        m_axi_mem_AWCACHE,
        m_axi_mem_AWPROT,
        m_axi_mem_AWQOS,
        m_axi_mem_AWREGION,
        m_axi_mem_AWUSER,
        m_axi_mem_WVALID,
        m_axi_mem_WREADY,
        m_axi_mem_WDATA,
        m_axi_mem_WSTRB,
        m_axi_mem_WLAST,
        m_axi_mem_WID,
        m_axi_mem_WUSER,
        m_axi_mem_ARVALID,
        m_axi_mem_ARREADY,
        m_axi_mem_ARADDR,
        m_axi_mem_ARID,
        m_axi_mem_ARLEN,
        m_axi_mem_ARSIZE,
        m_axi_mem_ARBURST,
        m_axi_mem_ARLOCK,
        m_axi_mem_ARCACHE,
        m_axi_mem_ARPROT,
        m_axi_mem_ARQOS,
        m_axi_mem_ARREGION,
        m_axi_mem_ARUSER,
        m_axi_mem_RVALID,
        m_axi_mem_RREADY,
        m_axi_mem_RDATA,
        m_axi_mem_RLAST,
        m_axi_mem_RID,
        m_axi_mem_RUSER,
        m_axi_mem_RRESP,
        m_axi_mem_BVALID,
        m_axi_mem_BREADY,
        m_axi_mem_BRESP,
        m_axi_mem_BID,
        m_axi_mem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_ID_WIDTH = 1;
parameter    C_M_AXI_MEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_MEM_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_USER_VALUE = 0;
parameter    C_M_AXI_MEM_PROT_VALUE = 0;
parameter    C_M_AXI_MEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_mem_AWVALID;
input   m_axi_mem_AWREADY;
output  [C_M_AXI_MEM_ADDR_WIDTH - 1:0] m_axi_mem_AWADDR;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_AWID;
output  [7:0] m_axi_mem_AWLEN;
output  [2:0] m_axi_mem_AWSIZE;
output  [1:0] m_axi_mem_AWBURST;
output  [1:0] m_axi_mem_AWLOCK;
output  [3:0] m_axi_mem_AWCACHE;
output  [2:0] m_axi_mem_AWPROT;
output  [3:0] m_axi_mem_AWQOS;
output  [3:0] m_axi_mem_AWREGION;
output  [C_M_AXI_MEM_AWUSER_WIDTH - 1:0] m_axi_mem_AWUSER;
output   m_axi_mem_WVALID;
input   m_axi_mem_WREADY;
output  [C_M_AXI_MEM_DATA_WIDTH - 1:0] m_axi_mem_WDATA;
output  [C_M_AXI_MEM_WSTRB_WIDTH - 1:0] m_axi_mem_WSTRB;
output   m_axi_mem_WLAST;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_WID;
output  [C_M_AXI_MEM_WUSER_WIDTH - 1:0] m_axi_mem_WUSER;
output   m_axi_mem_ARVALID;
input   m_axi_mem_ARREADY;
output  [C_M_AXI_MEM_ADDR_WIDTH - 1:0] m_axi_mem_ARADDR;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_ARID;
output  [7:0] m_axi_mem_ARLEN;
output  [2:0] m_axi_mem_ARSIZE;
output  [1:0] m_axi_mem_ARBURST;
output  [1:0] m_axi_mem_ARLOCK;
output  [3:0] m_axi_mem_ARCACHE;
output  [2:0] m_axi_mem_ARPROT;
output  [3:0] m_axi_mem_ARQOS;
output  [3:0] m_axi_mem_ARREGION;
output  [C_M_AXI_MEM_ARUSER_WIDTH - 1:0] m_axi_mem_ARUSER;
input   m_axi_mem_RVALID;
output   m_axi_mem_RREADY;
input  [C_M_AXI_MEM_DATA_WIDTH - 1:0] m_axi_mem_RDATA;
input   m_axi_mem_RLAST;
input  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_RID;
input  [C_M_AXI_MEM_RUSER_WIDTH - 1:0] m_axi_mem_RUSER;
input  [1:0] m_axi_mem_RRESP;
input   m_axi_mem_BVALID;
output   m_axi_mem_BREADY;
input  [1:0] m_axi_mem_BRESP;
input  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_BID;
input  [C_M_AXI_MEM_BUSER_WIDTH - 1:0] m_axi_mem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] MatA_DRAM;
wire   [63:0] MatB_DRAM;
wire   [63:0] MatC_DRAM;
reg    mem_blk_n_AR;
wire    ap_CS_fsm_state4;
reg   [63:0] MatC_DRAM_read_reg_415;
reg   [63:0] MatB_DRAM_read_reg_420;
reg   [63:0] MatA_DRAM_read_reg_425;
reg   [10:0] counter_1_reg_430;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln29_fu_252_p2;
wire   [6:0] shl_ln_fu_278_p3;
reg   [6:0] shl_ln_reg_443;
wire   [15:0] mul_ln30_fu_290_p2;
reg   [15:0] mul_ln30_reg_448;
reg   [62:0] trunc_ln_reg_453;
wire    ap_CS_fsm_state3;
wire   [13:0] grp_fu_386_p3;
reg  signed [13:0] add_ln30_1_reg_469;
wire    ap_CS_fsm_state5;
wire   [5:0] empty_24_fu_348_p1;
reg   [5:0] empty_24_reg_474;
wire    ap_CS_fsm_state14;
wire   [14:0] tmp_1_fu_378_p3;
reg   [14:0] tmp_1_reg_479;
wire    ap_CS_fsm_state18;
reg   [7:0] MatA_BRAM_address0;
reg    MatA_BRAM_ce0;
reg    MatA_BRAM_we0;
wire   [15:0] MatA_BRAM_q0;
reg    MatA_BRAM_ce1;
wire   [15:0] MatA_BRAM_q1;
reg   [7:0] MatA_BRAM_1_address0;
reg    MatA_BRAM_1_ce0;
reg    MatA_BRAM_1_we0;
wire   [15:0] MatA_BRAM_1_q0;
reg    MatA_BRAM_1_ce1;
wire   [15:0] MatA_BRAM_1_q1;
reg   [7:0] MatA_BRAM_2_address0;
reg    MatA_BRAM_2_ce0;
reg    MatA_BRAM_2_we0;
wire   [15:0] MatA_BRAM_2_q0;
reg    MatA_BRAM_2_ce1;
wire   [15:0] MatA_BRAM_2_q1;
reg   [7:0] MatA_BRAM_3_address0;
reg    MatA_BRAM_3_ce0;
reg    MatA_BRAM_3_we0;
wire   [15:0] MatA_BRAM_3_q0;
reg    MatA_BRAM_3_ce1;
wire   [15:0] MatA_BRAM_3_q1;
reg   [7:0] MatB_BRAM_address0;
reg    MatB_BRAM_ce0;
reg    MatB_BRAM_we0;
wire   [15:0] MatB_BRAM_q0;
reg    MatB_BRAM_ce1;
wire   [15:0] MatB_BRAM_q1;
reg   [7:0] MatB_BRAM_1_address0;
reg    MatB_BRAM_1_ce0;
reg    MatB_BRAM_1_we0;
wire   [15:0] MatB_BRAM_1_q0;
reg    MatB_BRAM_1_ce1;
wire   [15:0] MatB_BRAM_1_q1;
reg   [7:0] MatB_BRAM_2_address0;
reg    MatB_BRAM_2_ce0;
reg    MatB_BRAM_2_we0;
wire   [15:0] MatB_BRAM_2_q0;
reg    MatB_BRAM_2_ce1;
wire   [15:0] MatB_BRAM_2_q1;
reg   [7:0] MatB_BRAM_3_address0;
reg    MatB_BRAM_3_ce0;
reg    MatB_BRAM_3_we0;
wire   [15:0] MatB_BRAM_3_q0;
reg    MatB_BRAM_3_ce1;
wire   [15:0] MatB_BRAM_3_q1;
reg   [3:0] MatC_BRAM_address0;
reg    MatC_BRAM_ce0;
reg    MatC_BRAM_we0;
wire   [15:0] MatC_BRAM_q0;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_start;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_done;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_idle;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_ready;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWVALID;
wire   [63:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWADDR;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWID;
wire   [31:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWLEN;
wire   [2:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWSIZE;
wire   [1:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWBURST;
wire   [1:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWLOCK;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWCACHE;
wire   [2:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWPROT;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWQOS;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWREGION;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWUSER;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WVALID;
wire   [15:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WDATA;
wire   [1:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WSTRB;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WLAST;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WID;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WUSER;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARVALID;
wire   [63:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARADDR;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARID;
wire   [31:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARLEN;
wire   [2:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARSIZE;
wire   [1:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARBURST;
wire   [1:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARLOCK;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARCACHE;
wire   [2:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARPROT;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARQOS;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARREGION;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARUSER;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_RREADY;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_BREADY;
wire   [7:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_address0;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_ce0;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_we0;
wire   [15:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_d0;
wire   [7:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_address0;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_ce0;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_we0;
wire   [15:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_d0;
wire   [7:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_address0;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_ce0;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_we0;
wire   [15:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_d0;
wire   [7:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_address0;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_ce0;
wire    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_we0;
wire   [15:0] grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_d0;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_start;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_done;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_idle;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_ready;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWVALID;
wire   [63:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWADDR;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWID;
wire   [31:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWLEN;
wire   [2:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWSIZE;
wire   [1:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWBURST;
wire   [1:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWLOCK;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWCACHE;
wire   [2:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWPROT;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWQOS;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWREGION;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWUSER;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WVALID;
wire   [15:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WDATA;
wire   [1:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WSTRB;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WLAST;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WID;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WUSER;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARVALID;
wire   [63:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARADDR;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARID;
wire   [31:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARLEN;
wire   [2:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARSIZE;
wire   [1:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARBURST;
wire   [1:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARLOCK;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARCACHE;
wire   [2:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARPROT;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARQOS;
wire   [3:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARREGION;
wire   [0:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARUSER;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_RREADY;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_BREADY;
wire   [7:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_address0;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_ce0;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_we0;
wire   [15:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_d0;
wire   [7:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_address0;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_ce0;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_we0;
wire   [15:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_d0;
wire   [7:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_address0;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_ce0;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_we0;
wire   [15:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_d0;
wire   [7:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_address0;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_ce0;
wire    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_we0;
wire   [15:0] grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_d0;
wire    grp_PerformMatrixCalculation_fu_202_ap_start;
wire    grp_PerformMatrixCalculation_fu_202_ap_done;
wire    grp_PerformMatrixCalculation_fu_202_ap_idle;
wire    grp_PerformMatrixCalculation_fu_202_ap_ready;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_address0;
wire    grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_ce0;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_address1;
wire    grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_ce1;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_address0;
wire    grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_ce0;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_address1;
wire    grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_ce1;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_address0;
wire    grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_ce0;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_address1;
wire    grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_ce1;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_address0;
wire    grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_ce0;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_address1;
wire    grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_ce1;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_address0;
wire    grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_ce0;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_address1;
wire    grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_ce1;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_address0;
wire    grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_ce0;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_address1;
wire    grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_ce1;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_address0;
wire    grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_ce0;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_address1;
wire    grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_ce1;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_address0;
wire    grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_ce0;
wire   [7:0] grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_address1;
wire    grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_ce1;
wire   [3:0] grp_PerformMatrixCalculation_fu_202_MatC_BRAM_address0;
wire    grp_PerformMatrixCalculation_fu_202_MatC_BRAM_ce0;
wire    grp_PerformMatrixCalculation_fu_202_MatC_BRAM_we0;
wire   [15:0] grp_PerformMatrixCalculation_fu_202_MatC_BRAM_d0;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_start;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_done;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_idle;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_ready;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWVALID;
wire   [63:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWADDR;
wire   [0:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWID;
wire   [31:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWLEN;
wire   [2:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWSIZE;
wire   [1:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWBURST;
wire   [1:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWLOCK;
wire   [3:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWCACHE;
wire   [2:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWPROT;
wire   [3:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWQOS;
wire   [3:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWREGION;
wire   [0:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWUSER;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WVALID;
wire   [15:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WDATA;
wire   [1:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WSTRB;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WLAST;
wire   [0:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WID;
wire   [0:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WUSER;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARVALID;
wire   [63:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARADDR;
wire   [0:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARID;
wire   [31:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARLEN;
wire   [2:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARSIZE;
wire   [1:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARBURST;
wire   [1:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARLOCK;
wire   [3:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARCACHE;
wire   [2:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARPROT;
wire   [3:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARQOS;
wire   [3:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARREGION;
wire   [0:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARUSER;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_RREADY;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_BREADY;
wire   [3:0] grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_MatC_BRAM_address0;
wire    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_MatC_BRAM_ce0;
reg    mem_AWVALID;
wire    mem_AWREADY;
reg    mem_WVALID;
wire    mem_WREADY;
reg    mem_ARVALID;
wire    mem_ARREADY;
reg   [63:0] mem_ARADDR;
reg   [31:0] mem_ARLEN;
wire    mem_RVALID;
reg    mem_RREADY;
wire   [15:0] mem_RDATA;
wire   [9:0] mem_RFIFONUM;
wire    mem_BVALID;
reg    mem_BREADY;
reg    grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg    grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_start_reg;
wire    ap_CS_fsm_state15;
reg    grp_PerformMatrixCalculation_fu_202_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg    grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_start_reg;
wire    ap_CS_fsm_state19;
wire  signed [63:0] sext_ln48_fu_324_p1;
reg   [10:0] phi_urem_fu_106;
wire   [10:0] select_ln29_fu_365_p3;
reg   [21:0] phi_mul_fu_110;
wire   [21:0] add_ln29_fu_246_p2;
reg   [10:0] counter_fu_114;
wire   [10:0] counter_2_fu_258_p2;
wire   [4:0] tmp_fu_264_p4;
wire   [6:0] mul_ln30_fu_290_p0;
wire   [9:0] mul_ln30_fu_290_p1;
wire   [63:0] zext_ln30_2_fu_306_p1;
wire   [63:0] add_ln30_fu_309_p2;
wire   [12:0] shl_ln30_1_fu_334_p3;
wire   [10:0] add_ln29_2_fu_353_p2;
wire   [0:0] icmp_ln29_1_fu_359_p2;
wire   [4:0] grp_fu_386_p0;
wire  signed [8:0] grp_fu_386_p1;
wire   [12:0] grp_fu_386_p2;
reg    grp_fu_386_ce;
reg   [18:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire   [13:0] grp_fu_386_p00;
wire   [13:0] grp_fu_386_p20;
wire   [15:0] mul_ln30_fu_290_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 19'd1;
#0 grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_start_reg = 1'b0;
#0 grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_start_reg = 1'b0;
#0 grp_PerformMatrixCalculation_fu_202_ap_start_reg = 1'b0;
#0 grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_start_reg = 1'b0;
end

real_matmul_MatA_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatA_BRAM_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatA_BRAM_address0),
    .ce0(MatA_BRAM_ce0),
    .we0(MatA_BRAM_we0),
    .d0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_d0),
    .q0(MatA_BRAM_q0),
    .address1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_address1),
    .ce1(MatA_BRAM_ce1),
    .q1(MatA_BRAM_q1)
);

real_matmul_MatA_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatA_BRAM_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatA_BRAM_1_address0),
    .ce0(MatA_BRAM_1_ce0),
    .we0(MatA_BRAM_1_we0),
    .d0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_d0),
    .q0(MatA_BRAM_1_q0),
    .address1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_address1),
    .ce1(MatA_BRAM_1_ce1),
    .q1(MatA_BRAM_1_q1)
);

real_matmul_MatA_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatA_BRAM_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatA_BRAM_2_address0),
    .ce0(MatA_BRAM_2_ce0),
    .we0(MatA_BRAM_2_we0),
    .d0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_d0),
    .q0(MatA_BRAM_2_q0),
    .address1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_address1),
    .ce1(MatA_BRAM_2_ce1),
    .q1(MatA_BRAM_2_q1)
);

real_matmul_MatA_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatA_BRAM_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatA_BRAM_3_address0),
    .ce0(MatA_BRAM_3_ce0),
    .we0(MatA_BRAM_3_we0),
    .d0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_d0),
    .q0(MatA_BRAM_3_q0),
    .address1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_address1),
    .ce1(MatA_BRAM_3_ce1),
    .q1(MatA_BRAM_3_q1)
);

real_matmul_MatA_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatB_BRAM_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatB_BRAM_address0),
    .ce0(MatB_BRAM_ce0),
    .we0(MatB_BRAM_we0),
    .d0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_d0),
    .q0(MatB_BRAM_q0),
    .address1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_address1),
    .ce1(MatB_BRAM_ce1),
    .q1(MatB_BRAM_q1)
);

real_matmul_MatA_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatB_BRAM_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatB_BRAM_1_address0),
    .ce0(MatB_BRAM_1_ce0),
    .we0(MatB_BRAM_1_we0),
    .d0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_d0),
    .q0(MatB_BRAM_1_q0),
    .address1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_address1),
    .ce1(MatB_BRAM_1_ce1),
    .q1(MatB_BRAM_1_q1)
);

real_matmul_MatA_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatB_BRAM_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatB_BRAM_2_address0),
    .ce0(MatB_BRAM_2_ce0),
    .we0(MatB_BRAM_2_we0),
    .d0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_d0),
    .q0(MatB_BRAM_2_q0),
    .address1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_address1),
    .ce1(MatB_BRAM_2_ce1),
    .q1(MatB_BRAM_2_q1)
);

real_matmul_MatA_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
MatB_BRAM_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatB_BRAM_3_address0),
    .ce0(MatB_BRAM_3_ce0),
    .we0(MatB_BRAM_3_we0),
    .d0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_d0),
    .q0(MatB_BRAM_3_q0),
    .address1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_address1),
    .ce1(MatB_BRAM_3_ce1),
    .q1(MatB_BRAM_3_q1)
);

real_matmul_MatC_BRAM_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
MatC_BRAM_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatC_BRAM_address0),
    .ce0(MatC_BRAM_ce0),
    .we0(MatC_BRAM_we0),
    .d0(grp_PerformMatrixCalculation_fu_202_MatC_BRAM_d0),
    .q0(MatC_BRAM_q0)
);

real_matmul_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1 grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_start),
    .ap_done(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_done),
    .ap_idle(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_idle),
    .ap_ready(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_ready),
    .m_axi_mem_AWVALID(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWVALID),
    .m_axi_mem_AWREADY(1'b0),
    .m_axi_mem_AWADDR(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWADDR),
    .m_axi_mem_AWID(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWID),
    .m_axi_mem_AWLEN(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWLEN),
    .m_axi_mem_AWSIZE(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWSIZE),
    .m_axi_mem_AWBURST(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWBURST),
    .m_axi_mem_AWLOCK(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWLOCK),
    .m_axi_mem_AWCACHE(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWCACHE),
    .m_axi_mem_AWPROT(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWPROT),
    .m_axi_mem_AWQOS(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWQOS),
    .m_axi_mem_AWREGION(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWREGION),
    .m_axi_mem_AWUSER(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_AWUSER),
    .m_axi_mem_WVALID(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WVALID),
    .m_axi_mem_WREADY(1'b0),
    .m_axi_mem_WDATA(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WDATA),
    .m_axi_mem_WSTRB(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WSTRB),
    .m_axi_mem_WLAST(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WLAST),
    .m_axi_mem_WID(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WID),
    .m_axi_mem_WUSER(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_WUSER),
    .m_axi_mem_ARVALID(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARVALID),
    .m_axi_mem_ARREADY(mem_ARREADY),
    .m_axi_mem_ARADDR(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARADDR),
    .m_axi_mem_ARID(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARID),
    .m_axi_mem_ARLEN(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARLEN),
    .m_axi_mem_ARSIZE(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARSIZE),
    .m_axi_mem_ARBURST(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARBURST),
    .m_axi_mem_ARLOCK(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARLOCK),
    .m_axi_mem_ARCACHE(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARCACHE),
    .m_axi_mem_ARPROT(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARPROT),
    .m_axi_mem_ARQOS(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARQOS),
    .m_axi_mem_ARREGION(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARREGION),
    .m_axi_mem_ARUSER(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARUSER),
    .m_axi_mem_RVALID(mem_RVALID),
    .m_axi_mem_RREADY(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_RREADY),
    .m_axi_mem_RDATA(mem_RDATA),
    .m_axi_mem_RLAST(1'b0),
    .m_axi_mem_RID(1'd0),
    .m_axi_mem_RFIFONUM(mem_RFIFONUM),
    .m_axi_mem_RUSER(1'd0),
    .m_axi_mem_RRESP(2'd0),
    .m_axi_mem_BVALID(1'b0),
    .m_axi_mem_BREADY(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_BREADY),
    .m_axi_mem_BRESP(2'd0),
    .m_axi_mem_BID(1'd0),
    .m_axi_mem_BUSER(1'd0),
    .sext_ln48(trunc_ln_reg_453),
    .MatA_BRAM_3_address0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_address0),
    .MatA_BRAM_3_ce0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_ce0),
    .MatA_BRAM_3_we0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_we0),
    .MatA_BRAM_3_d0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_d0),
    .MatA_BRAM_2_address0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_address0),
    .MatA_BRAM_2_ce0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_ce0),
    .MatA_BRAM_2_we0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_we0),
    .MatA_BRAM_2_d0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_d0),
    .MatA_BRAM_1_address0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_address0),
    .MatA_BRAM_1_ce0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_ce0),
    .MatA_BRAM_1_we0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_we0),
    .MatA_BRAM_1_d0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_d0),
    .MatA_BRAM_address0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_address0),
    .MatA_BRAM_ce0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_ce0),
    .MatA_BRAM_we0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_we0),
    .MatA_BRAM_d0(grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_d0)
);

real_matmul_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2 grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_start),
    .ap_done(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_done),
    .ap_idle(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_idle),
    .ap_ready(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_ready),
    .m_axi_mem_AWVALID(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWVALID),
    .m_axi_mem_AWREADY(1'b0),
    .m_axi_mem_AWADDR(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWADDR),
    .m_axi_mem_AWID(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWID),
    .m_axi_mem_AWLEN(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWLEN),
    .m_axi_mem_AWSIZE(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWSIZE),
    .m_axi_mem_AWBURST(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWBURST),
    .m_axi_mem_AWLOCK(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWLOCK),
    .m_axi_mem_AWCACHE(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWCACHE),
    .m_axi_mem_AWPROT(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWPROT),
    .m_axi_mem_AWQOS(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWQOS),
    .m_axi_mem_AWREGION(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWREGION),
    .m_axi_mem_AWUSER(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_AWUSER),
    .m_axi_mem_WVALID(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WVALID),
    .m_axi_mem_WREADY(1'b0),
    .m_axi_mem_WDATA(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WDATA),
    .m_axi_mem_WSTRB(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WSTRB),
    .m_axi_mem_WLAST(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WLAST),
    .m_axi_mem_WID(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WID),
    .m_axi_mem_WUSER(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_WUSER),
    .m_axi_mem_ARVALID(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARVALID),
    .m_axi_mem_ARREADY(mem_ARREADY),
    .m_axi_mem_ARADDR(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARADDR),
    .m_axi_mem_ARID(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARID),
    .m_axi_mem_ARLEN(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARLEN),
    .m_axi_mem_ARSIZE(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARSIZE),
    .m_axi_mem_ARBURST(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARBURST),
    .m_axi_mem_ARLOCK(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARLOCK),
    .m_axi_mem_ARCACHE(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARCACHE),
    .m_axi_mem_ARPROT(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARPROT),
    .m_axi_mem_ARQOS(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARQOS),
    .m_axi_mem_ARREGION(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARREGION),
    .m_axi_mem_ARUSER(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARUSER),
    .m_axi_mem_RVALID(mem_RVALID),
    .m_axi_mem_RREADY(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_RREADY),
    .m_axi_mem_RDATA(mem_RDATA),
    .m_axi_mem_RLAST(1'b0),
    .m_axi_mem_RID(1'd0),
    .m_axi_mem_RFIFONUM(mem_RFIFONUM),
    .m_axi_mem_RUSER(1'd0),
    .m_axi_mem_RRESP(2'd0),
    .m_axi_mem_BVALID(1'b0),
    .m_axi_mem_BREADY(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_BREADY),
    .m_axi_mem_BRESP(2'd0),
    .m_axi_mem_BID(1'd0),
    .m_axi_mem_BUSER(1'd0),
    .MatB_BRAM_3_address0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_address0),
    .MatB_BRAM_3_ce0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_ce0),
    .MatB_BRAM_3_we0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_we0),
    .MatB_BRAM_3_d0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_d0),
    .MatB_BRAM_2_address0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_address0),
    .MatB_BRAM_2_ce0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_ce0),
    .MatB_BRAM_2_we0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_we0),
    .MatB_BRAM_2_d0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_d0),
    .MatB_BRAM_1_address0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_address0),
    .MatB_BRAM_1_ce0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_ce0),
    .MatB_BRAM_1_we0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_we0),
    .MatB_BRAM_1_d0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_d0),
    .MatB_BRAM_address0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_address0),
    .MatB_BRAM_ce0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_ce0),
    .MatB_BRAM_we0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_we0),
    .MatB_BRAM_d0(grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_d0),
    .rem_i_urem_cast(empty_24_reg_474),
    .MatB_DRAM(MatB_DRAM_read_reg_420)
);

real_matmul_PerformMatrixCalculation grp_PerformMatrixCalculation_fu_202(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_PerformMatrixCalculation_fu_202_ap_start),
    .ap_done(grp_PerformMatrixCalculation_fu_202_ap_done),
    .ap_idle(grp_PerformMatrixCalculation_fu_202_ap_idle),
    .ap_ready(grp_PerformMatrixCalculation_fu_202_ap_ready),
    .MatA_BRAM_0_address0(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_address0),
    .MatA_BRAM_0_ce0(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_ce0),
    .MatA_BRAM_0_q0(MatA_BRAM_q0),
    .MatA_BRAM_0_address1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_address1),
    .MatA_BRAM_0_ce1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_ce1),
    .MatA_BRAM_0_q1(MatA_BRAM_q1),
    .MatA_BRAM_1_address0(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_address0),
    .MatA_BRAM_1_ce0(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_ce0),
    .MatA_BRAM_1_q0(MatA_BRAM_1_q0),
    .MatA_BRAM_1_address1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_address1),
    .MatA_BRAM_1_ce1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_ce1),
    .MatA_BRAM_1_q1(MatA_BRAM_1_q1),
    .MatA_BRAM_2_address0(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_address0),
    .MatA_BRAM_2_ce0(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_ce0),
    .MatA_BRAM_2_q0(MatA_BRAM_2_q0),
    .MatA_BRAM_2_address1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_address1),
    .MatA_BRAM_2_ce1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_ce1),
    .MatA_BRAM_2_q1(MatA_BRAM_2_q1),
    .MatA_BRAM_3_address0(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_address0),
    .MatA_BRAM_3_ce0(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_ce0),
    .MatA_BRAM_3_q0(MatA_BRAM_3_q0),
    .MatA_BRAM_3_address1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_address1),
    .MatA_BRAM_3_ce1(grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_ce1),
    .MatA_BRAM_3_q1(MatA_BRAM_3_q1),
    .MatB_BRAM_0_address0(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_address0),
    .MatB_BRAM_0_ce0(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_ce0),
    .MatB_BRAM_0_q0(MatB_BRAM_q0),
    .MatB_BRAM_0_address1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_address1),
    .MatB_BRAM_0_ce1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_ce1),
    .MatB_BRAM_0_q1(MatB_BRAM_q1),
    .MatB_BRAM_1_address0(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_address0),
    .MatB_BRAM_1_ce0(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_ce0),
    .MatB_BRAM_1_q0(MatB_BRAM_1_q0),
    .MatB_BRAM_1_address1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_address1),
    .MatB_BRAM_1_ce1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_ce1),
    .MatB_BRAM_1_q1(MatB_BRAM_1_q1),
    .MatB_BRAM_2_address0(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_address0),
    .MatB_BRAM_2_ce0(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_ce0),
    .MatB_BRAM_2_q0(MatB_BRAM_2_q0),
    .MatB_BRAM_2_address1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_address1),
    .MatB_BRAM_2_ce1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_ce1),
    .MatB_BRAM_2_q1(MatB_BRAM_2_q1),
    .MatB_BRAM_3_address0(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_address0),
    .MatB_BRAM_3_ce0(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_ce0),
    .MatB_BRAM_3_q0(MatB_BRAM_3_q0),
    .MatB_BRAM_3_address1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_address1),
    .MatB_BRAM_3_ce1(grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_ce1),
    .MatB_BRAM_3_q1(MatB_BRAM_3_q1),
    .MatC_BRAM_address0(grp_PerformMatrixCalculation_fu_202_MatC_BRAM_address0),
    .MatC_BRAM_ce0(grp_PerformMatrixCalculation_fu_202_MatC_BRAM_ce0),
    .MatC_BRAM_we0(grp_PerformMatrixCalculation_fu_202_MatC_BRAM_we0),
    .MatC_BRAM_d0(grp_PerformMatrixCalculation_fu_202_MatC_BRAM_d0)
);

real_matmul_real_matmul_Pipeline_VITIS_LOOP_78_1 grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_start),
    .ap_done(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_done),
    .ap_idle(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_idle),
    .ap_ready(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_ready),
    .m_axi_mem_AWVALID(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWVALID),
    .m_axi_mem_AWREADY(mem_AWREADY),
    .m_axi_mem_AWADDR(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWADDR),
    .m_axi_mem_AWID(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWID),
    .m_axi_mem_AWLEN(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWLEN),
    .m_axi_mem_AWSIZE(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWSIZE),
    .m_axi_mem_AWBURST(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWBURST),
    .m_axi_mem_AWLOCK(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWLOCK),
    .m_axi_mem_AWCACHE(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWCACHE),
    .m_axi_mem_AWPROT(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWPROT),
    .m_axi_mem_AWQOS(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWQOS),
    .m_axi_mem_AWREGION(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWREGION),
    .m_axi_mem_AWUSER(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWUSER),
    .m_axi_mem_WVALID(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WVALID),
    .m_axi_mem_WREADY(mem_WREADY),
    .m_axi_mem_WDATA(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WDATA),
    .m_axi_mem_WSTRB(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WSTRB),
    .m_axi_mem_WLAST(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WLAST),
    .m_axi_mem_WID(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WID),
    .m_axi_mem_WUSER(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WUSER),
    .m_axi_mem_ARVALID(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARVALID),
    .m_axi_mem_ARREADY(1'b0),
    .m_axi_mem_ARADDR(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARADDR),
    .m_axi_mem_ARID(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARID),
    .m_axi_mem_ARLEN(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARLEN),
    .m_axi_mem_ARSIZE(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARSIZE),
    .m_axi_mem_ARBURST(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARBURST),
    .m_axi_mem_ARLOCK(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARLOCK),
    .m_axi_mem_ARCACHE(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARCACHE),
    .m_axi_mem_ARPROT(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARPROT),
    .m_axi_mem_ARQOS(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARQOS),
    .m_axi_mem_ARREGION(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARREGION),
    .m_axi_mem_ARUSER(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_ARUSER),
    .m_axi_mem_RVALID(1'b0),
    .m_axi_mem_RREADY(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_RREADY),
    .m_axi_mem_RDATA(16'd0),
    .m_axi_mem_RLAST(1'b0),
    .m_axi_mem_RID(1'd0),
    .m_axi_mem_RFIFONUM(10'd0),
    .m_axi_mem_RUSER(1'd0),
    .m_axi_mem_RRESP(2'd0),
    .m_axi_mem_BVALID(mem_BVALID),
    .m_axi_mem_BREADY(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_BREADY),
    .m_axi_mem_BRESP(2'd0),
    .m_axi_mem_BID(1'd0),
    .m_axi_mem_BUSER(1'd0),
    .shl_ln(shl_ln_reg_443),
    .MatC_DRAM(MatC_DRAM_read_reg_415),
    .sext_ln77(tmp_1_reg_479),
    .MatC_BRAM_address0(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_MatC_BRAM_address0),
    .MatC_BRAM_ce0(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_MatC_BRAM_ce0),
    .MatC_BRAM_q0(MatC_BRAM_q0)
);

real_matmul_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .MatA_DRAM(MatA_DRAM),
    .MatB_DRAM(MatB_DRAM),
    .MatC_DRAM(MatC_DRAM),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

real_matmul_mem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 10 ),
    .USER_DW( 16 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
mem_m_axi_U(
    .AWVALID(m_axi_mem_AWVALID),
    .AWREADY(m_axi_mem_AWREADY),
    .AWADDR(m_axi_mem_AWADDR),
    .AWID(m_axi_mem_AWID),
    .AWLEN(m_axi_mem_AWLEN),
    .AWSIZE(m_axi_mem_AWSIZE),
    .AWBURST(m_axi_mem_AWBURST),
    .AWLOCK(m_axi_mem_AWLOCK),
    .AWCACHE(m_axi_mem_AWCACHE),
    .AWPROT(m_axi_mem_AWPROT),
    .AWQOS(m_axi_mem_AWQOS),
    .AWREGION(m_axi_mem_AWREGION),
    .AWUSER(m_axi_mem_AWUSER),
    .WVALID(m_axi_mem_WVALID),
    .WREADY(m_axi_mem_WREADY),
    .WDATA(m_axi_mem_WDATA),
    .WSTRB(m_axi_mem_WSTRB),
    .WLAST(m_axi_mem_WLAST),
    .WID(m_axi_mem_WID),
    .WUSER(m_axi_mem_WUSER),
    .ARVALID(m_axi_mem_ARVALID),
    .ARREADY(m_axi_mem_ARREADY),
    .ARADDR(m_axi_mem_ARADDR),
    .ARID(m_axi_mem_ARID),
    .ARLEN(m_axi_mem_ARLEN),
    .ARSIZE(m_axi_mem_ARSIZE),
    .ARBURST(m_axi_mem_ARBURST),
    .ARLOCK(m_axi_mem_ARLOCK),
    .ARCACHE(m_axi_mem_ARCACHE),
    .ARPROT(m_axi_mem_ARPROT),
    .ARQOS(m_axi_mem_ARQOS),
    .ARREGION(m_axi_mem_ARREGION),
    .ARUSER(m_axi_mem_ARUSER),
    .RVALID(m_axi_mem_RVALID),
    .RREADY(m_axi_mem_RREADY),
    .RDATA(m_axi_mem_RDATA),
    .RLAST(m_axi_mem_RLAST),
    .RID(m_axi_mem_RID),
    .RUSER(m_axi_mem_RUSER),
    .RRESP(m_axi_mem_RRESP),
    .BVALID(m_axi_mem_BVALID),
    .BREADY(m_axi_mem_BREADY),
    .BRESP(m_axi_mem_BRESP),
    .BID(m_axi_mem_BID),
    .BUSER(m_axi_mem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(mem_ARVALID),
    .I_ARREADY(mem_ARREADY),
    .I_ARADDR(mem_ARADDR),
    .I_ARLEN(mem_ARLEN),
    .I_RVALID(mem_RVALID),
    .I_RREADY(mem_RREADY),
    .I_RDATA(mem_RDATA),
    .I_RFIFONUM(mem_RFIFONUM),
    .I_AWVALID(mem_AWVALID),
    .I_AWREADY(mem_AWREADY),
    .I_AWADDR(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWADDR),
    .I_AWLEN(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWLEN),
    .I_WVALID(mem_WVALID),
    .I_WREADY(mem_WREADY),
    .I_WDATA(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WDATA),
    .I_WSTRB(grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WSTRB),
    .I_BVALID(mem_BVALID),
    .I_BREADY(mem_BREADY)
);

real_matmul_mul_7ns_10ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 16 ))
mul_7ns_10ns_16_1_1_U1836(
    .din0(mul_ln30_fu_290_p0),
    .din1(mul_ln30_fu_290_p1),
    .dout(mul_ln30_fu_290_p2)
);

real_matmul_mac_muladd_5ns_9s_13ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 14 ))
mac_muladd_5ns_9s_13ns_14_4_1_U1837(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_386_p0),
    .din1(grp_fu_386_p1),
    .din2(grp_fu_386_p2),
    .ce(grp_fu_386_ce),
    .dout(grp_fu_386_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_PerformMatrixCalculation_fu_202_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_PerformMatrixCalculation_fu_202_ap_start_reg <= 1'b1;
        end else if ((grp_PerformMatrixCalculation_fu_202_ap_ready == 1'b1)) begin
            grp_PerformMatrixCalculation_fu_202_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_start_reg <= 1'b1;
        end else if ((grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_ready == 1'b1)) begin
            grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_start_reg <= 1'b1;
        end else if ((grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_ready == 1'b1)) begin
            grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_start_reg <= 1'b1;
        end else if ((grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_ready == 1'b1)) begin
            grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        counter_fu_114 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln29_fu_252_p2 == 1'd0))) begin
        counter_fu_114 <= counter_2_fu_258_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_fu_110 <= 22'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln29_fu_252_p2 == 1'd0))) begin
        phi_mul_fu_110 <= add_ln29_fu_246_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_urem_fu_106 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        phi_urem_fu_106 <= select_ln29_fu_365_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        MatA_DRAM_read_reg_425 <= MatA_DRAM;
        MatB_DRAM_read_reg_420 <= MatB_DRAM;
        MatC_DRAM_read_reg_415 <= MatC_DRAM;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln30_1_reg_469 <= grp_fu_386_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        counter_1_reg_430 <= counter_fu_114;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        empty_24_reg_474 <= empty_24_fu_348_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln29_fu_252_p2 == 1'd0))) begin
        mul_ln30_reg_448 <= mul_ln30_fu_290_p2;
        shl_ln_reg_443[6 : 2] <= shl_ln_fu_278_p3[6 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        tmp_1_reg_479[14 : 1] <= tmp_1_fu_378_p3[14 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln_reg_453 <= {{add_ln30_fu_309_p2[63:1]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_1_address0 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_1_address0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_address0;
    end else begin
        MatA_BRAM_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_1_ce0 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_1_ce0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_ce0;
    end else begin
        MatA_BRAM_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_1_ce1 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_1_ce1;
    end else begin
        MatA_BRAM_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_1_we0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_1_we0;
    end else begin
        MatA_BRAM_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_2_address0 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_2_address0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_address0;
    end else begin
        MatA_BRAM_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_2_ce0 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_2_ce0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_ce0;
    end else begin
        MatA_BRAM_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_2_ce1 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_2_ce1;
    end else begin
        MatA_BRAM_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_2_we0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_2_we0;
    end else begin
        MatA_BRAM_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_3_address0 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_3_address0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_address0;
    end else begin
        MatA_BRAM_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_3_ce0 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_3_ce0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_ce0;
    end else begin
        MatA_BRAM_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_3_ce1 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_3_ce1;
    end else begin
        MatA_BRAM_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_3_we0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_3_we0;
    end else begin
        MatA_BRAM_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_address0 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_address0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_address0;
    end else begin
        MatA_BRAM_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_ce0 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_ce0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_ce0;
    end else begin
        MatA_BRAM_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatA_BRAM_ce1 = grp_PerformMatrixCalculation_fu_202_MatA_BRAM_0_ce1;
    end else begin
        MatA_BRAM_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        MatA_BRAM_we0 = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_MatA_BRAM_we0;
    end else begin
        MatA_BRAM_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_1_address0 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_1_address0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_address0;
    end else begin
        MatB_BRAM_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_1_ce0 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_1_ce0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_ce0;
    end else begin
        MatB_BRAM_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_1_ce1 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_1_ce1;
    end else begin
        MatB_BRAM_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_1_we0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_1_we0;
    end else begin
        MatB_BRAM_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_2_address0 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_2_address0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_address0;
    end else begin
        MatB_BRAM_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_2_ce0 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_2_ce0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_ce0;
    end else begin
        MatB_BRAM_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_2_ce1 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_2_ce1;
    end else begin
        MatB_BRAM_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_2_we0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_2_we0;
    end else begin
        MatB_BRAM_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_3_address0 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_3_address0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_address0;
    end else begin
        MatB_BRAM_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_3_ce0 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_3_ce0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_ce0;
    end else begin
        MatB_BRAM_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_3_ce1 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_3_ce1;
    end else begin
        MatB_BRAM_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_3_we0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_3_we0;
    end else begin
        MatB_BRAM_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_address0 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_address0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_address0;
    end else begin
        MatB_BRAM_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_ce0 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_ce0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_ce0;
    end else begin
        MatB_BRAM_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatB_BRAM_ce1 = grp_PerformMatrixCalculation_fu_202_MatB_BRAM_0_ce1;
    end else begin
        MatB_BRAM_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        MatB_BRAM_we0 = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_MatB_BRAM_we0;
    end else begin
        MatB_BRAM_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        MatC_BRAM_address0 = grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_MatC_BRAM_address0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        MatC_BRAM_address0 = grp_PerformMatrixCalculation_fu_202_MatC_BRAM_address0;
    end else begin
        MatC_BRAM_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        MatC_BRAM_ce0 = grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_MatC_BRAM_ce0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        MatC_BRAM_ce0 = grp_PerformMatrixCalculation_fu_202_MatC_BRAM_ce0;
    end else begin
        MatC_BRAM_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        MatC_BRAM_we0 = grp_PerformMatrixCalculation_fu_202_MatC_BRAM_we0;
    end else begin
        MatC_BRAM_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_PerformMatrixCalculation_fu_202_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((mem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln29_fu_252_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln29_fu_252_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        grp_fu_386_ce = 1'b1;
    end else begin
        grp_fu_386_ce = 1'b0;
    end
end

always @ (*) begin
    if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mem_ARADDR = sext_ln48_fu_324_p1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        mem_ARADDR = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        mem_ARADDR = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARADDR;
    end else begin
        mem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mem_ARLEN = 32'd600;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        mem_ARLEN = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        mem_ARLEN = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARLEN;
    end else begin
        mem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        mem_ARVALID = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        mem_ARVALID = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_ARVALID;
    end else begin
        mem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        mem_AWVALID = grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_AWVALID;
    end else begin
        mem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        mem_BREADY = grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_BREADY;
    end else begin
        mem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        mem_RREADY = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_m_axi_mem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        mem_RREADY = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_m_axi_mem_RREADY;
    end else begin
        mem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        mem_WVALID = grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_m_axi_mem_WVALID;
    end else begin
        mem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mem_blk_n_AR = m_axi_mem_ARREADY;
    end else begin
        mem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln29_fu_252_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_PerformMatrixCalculation_fu_202_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln29_2_fu_353_p2 = (phi_urem_fu_106 + 11'd1);

assign add_ln29_fu_246_p2 = (phi_mul_fu_110 + 22'd2622);

assign add_ln30_fu_309_p2 = (zext_ln30_2_fu_306_p1 + MatA_DRAM_read_reg_425);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign counter_2_fu_258_p2 = (counter_fu_114 + 11'd1);

assign empty_24_fu_348_p1 = phi_urem_fu_106[5:0];

assign grp_PerformMatrixCalculation_fu_202_ap_start = grp_PerformMatrixCalculation_fu_202_ap_start_reg;

assign grp_fu_386_p0 = grp_fu_386_p00;

assign grp_fu_386_p00 = tmp_fu_264_p4;

assign grp_fu_386_p1 = 14'd16184;

assign grp_fu_386_p2 = grp_fu_386_p20;

assign grp_fu_386_p20 = shl_ln30_1_fu_334_p3;

assign grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_start = grp_real_matmul_Pipeline_LoadMatAFromDRAMtoBRAM_VITIS_LOOP_49_1_fu_179_ap_start_reg;

assign grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_start = grp_real_matmul_Pipeline_LoadMatBFromDRAMtoBRAM_VITIS_LOOP_56_2_fu_190_ap_start_reg;

assign grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_start = grp_real_matmul_Pipeline_VITIS_LOOP_78_1_fu_215_ap_start_reg;

assign icmp_ln29_1_fu_359_p2 = ((add_ln29_2_fu_353_p2 < 11'd50) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_252_p2 = ((counter_fu_114 == 11'd1250) ? 1'b1 : 1'b0);

assign mul_ln30_fu_290_p0 = mul_ln30_fu_290_p00;

assign mul_ln30_fu_290_p00 = shl_ln_fu_278_p3;

assign mul_ln30_fu_290_p1 = 16'd300;

assign select_ln29_fu_365_p3 = ((icmp_ln29_1_fu_359_p2[0:0] == 1'b1) ? add_ln29_2_fu_353_p2 : 11'd0);

assign sext_ln48_fu_324_p1 = $signed(trunc_ln_reg_453);

assign shl_ln30_1_fu_334_p3 = {{counter_1_reg_430}, {2'd0}};

assign shl_ln_fu_278_p3 = {{tmp_fu_264_p4}, {2'd0}};

assign tmp_1_fu_378_p3 = {{add_ln30_1_reg_469}, {1'd0}};

assign tmp_fu_264_p4 = {{phi_mul_fu_110[21:17]}};

assign zext_ln30_2_fu_306_p1 = mul_ln30_reg_448;

always @ (posedge ap_clk) begin
    shl_ln_reg_443[1:0] <= 2'b00;
    tmp_1_reg_479[0] <= 1'b0;
end

endmodule //real_matmul
